### ISSUE TITLE
It's not possible to take screenshot from a PNG file.

### ISSUE THREAD

**Issue by juninho** [mozilla-services/screenshots#2966] opened 2017-06-04 19:16 UTC
System: Debian SID (+ Firefox Nightly).
Steps to reproduce:
1 - On nautilus, right click on PNG file and open with firefox;
2 - Click 'Take Screenshot button';
3 - Select a region and save.

Result:
"We're not sure what just happened (...)".

BTW, this message could be improved and offers the possibility to go to the issues page to report an possible error.

**Comment by ianb** [comment] 2017-06-05 16:16
I'm not able to reproduce, I tried taking a screenshot of [this image](https://s3.amazonaws.com/nautilus-vertical/abstractions_0x0_476x316_a-212.jpeg) and it worked fine – though I suppose that's a JPG and not a PNG.  [This SVG](https://screenshots.firefox.com/static/img/landing-screenshots_image_02.svg) did *not* work, as the SVG is the document (we should treat it similar to framesets).  [This PNG](https://screenshots.firefox.com/static/img/icon-32.png) does work for me.

I opened a ticket for SVGs: #2967

**Comment by juninho** [comment] 2017-06-07 12:55
It tried again with the current nightly and can reproduce.
It only happens on local files opened in Firefox.

I tried with [this](https://cloud.githubusercontent.com/assets/498560/26037160/43348d42-38c4-11e7-8c6a-5fe5baad8679.png) PNG. Doing it online works, but after saving to my computer, it doesn't work anymore.

**Comment by SoftVision-CosminMuntean** [comment] 2017-06-08 13:35
Based on the latest comment, I suspect that this error is similar with the error described in issue: #2979.

**Comment by ianb** [comment] 2017-06-09 18:32
Yes, local file capture was broken in 9.0.0.  This should be fixed in 10.0.0

**Closed by ianb** 2017-06-09 18:32 UTC
