### ISSUE TITLE
Selecting expiration time not possible with low width

### ISSUE THREAD

**Issue by rugk** [mozilla-services/screenshots#4443] opened 2018-05-13 19:52 UTC
This looks like a CSS problem here:

![](https://screenshotscdn.firefoxusercontent.com/images/7d04ec89-7ddd-421d-92de-63f3f7d29764.png)

(https://screenshots.firefox.com/cEjeAKjj4Iu8Qkdv/screenshots.firefox.com)

1.024px × 682px

**Comment by Softvision-CristinaBadescu** [comment] 2018-05-14 08:01
Thanks for reporting this. However, this is a dupe of #3562 .

**Closed by Softvision-CristinaBadescu** 2018-05-14 08:01 UTC
