### ISSUE TITLE
Allow me to obfuscate (blur) certain parts of the screenshot, e.g. faces, usernames

### ISSUE THREAD

**Issue by jnachtigall** [mozilla-services/screenshots#1652] opened 2016-09-30 08:47 UTC
Greenshot, shutter and other screenshot tools have this feature that I can obfuscate / pixelate / blur certain parts of a screenshot. Usually some confidential data like a certain username, URL or faces. 

Would be nice if this would be possible.

**Comment by wresuolc** [comment] 2017-11-09 20:36
#3112 is probably the closest dupe of this, but if you search for "Annotations" in the issues you'll see several related issues.  The good news is we're working on this feature now. :)

**Closed by wresuolc** 2017-11-09 20:36 UTC
