### ISSUE TITLE
"callBackground is not defined" error is displayed after copy/paste hotkey is used on a page where Screenshots was used

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#4113] opened 2018-02-14 17:11 UTC
## STR
1. Go to a data studio report
2. Make sure you're in edit mode
3. take a shot and copy to clipboard
4. Try to copy/paste an element on the page (i used cmnd + c, cmnd + v)

## Results
This triggers a _haywire_ message every time you copy until you refresh the page!

**Comment by johngruen** [comment] 2018-02-15 16:53
```
Unhandled error: <unavailable> undefined  catcher.js:16
Unhandled error: Object { fromMakeError: true, name: "ReferenceError", message: "ReferenceError: callBackground is n…", stack: "keydownHandler@moz-extension://8dc4…" } undefined  catcher.js:16:7
	exports.unhandled moz-extension://8dc417f4-a6a4-3a43-88cd-ca9d623e0785/catcher.js:16:7
	<anonymous> moz-extension://8dc417f4-a6a4-3a43-88cd-ca9d623e0785/background/senderror.js:55:5
	exports.onMessage< moz-extension://8dc417f4-a6a4-3a43-88cd-ca9d623e0785/background/communication.js:25:16
	watchFunction/< moz-extension://8dc417f4-a6a4-3a43-88cd-ca9d623e0785/catcher.js:54:16
	<anonymous> moz-extension://8dc417f4-a6a4-3a43-88cd-ca9d623e0785/background/startBackground.js:49:14
	(Async: promise callback)
	<anonymous> moz-extension://8dc417f4-a6a4-3a43-88cd-ca9d623e0785/background/startBackground.js:48:5
```

**Comment by ianb** [comment] 2018-02-15 16:54
It looks like there's a teardown problem, where not everything is unloaded, and presumably the copy keyboard shortcut is left attached. The error message comes from the partially-unloaded code.

**Comment by chenba** [comment] 2018-02-15 17:29
I can reproduce this on latest Windows 10 Nightly.  My stack trace looks a little different:

```
ReferenceError: callBackground is not defined
Stack trace:
keydownHandler@moz-extension://69d37801-9421-41d4-a012-9e14702888da/selector/uicontrol.js:993:7
assertIsTrusted/<@moz-extension://69d37801-9421-41d4-a012-9e14702888da/assertIsTrusted.js:17:12
watchFunction/this.catcher@moz-extension://69d37801-9421-41d4-a012-9e14702888da/catcher.js:54:16
EventListener.handleEvent*start/<@moz-extension://69d37801-9421-41d4-a012-9e14702888da/selector/uicontrol.js:435:9
promise callback*start@moz-extension://69d37801-9421-41d4-a012-9e14702888da/selector/uicontrol.js:428:20
setState@moz-extension://69d37801-9421-41d4-a012-9e14702888da/selector/uicontrol.js:236:7
exports.activate@moz-extension://69d37801-9421-41d4-a012-9e14702888da/selector/uicontrol.js:907:7
watchFunction/this.catcher@moz-extension://69d37801-9421-41d4-a012-9e14702888da/catcher.js:54:16
this.uicontrol<@moz-extension://69d37801-9421-41d4-a012-9e14702888da/selector/uicontrol.js:1037:3
@moz-extension://69d37801-9421-41d4-a012-9e14702888da/selector/uicontrol.js:6:19
```

**Comment by johngruen** [comment] 2018-02-16 08:28
I was also able to reproduce this on the new Theming experiment in Nightly. Fortunately cannot repro in release.

https://mozilla.github.io/ThemesRFun/

**Comment by johngruen** [comment] 2018-02-16 08:29
@SoftVision-CosminMuntean could you test on Beta...i want to see if we might need an uplift here.

**Comment by SoftVision-CosminMuntean** [comment] 2018-02-16 09:13
This issue is not reproducible on latest Beta 59.0b9 build and latest Firefox 58.0.2 release.
It seems that the issue is only reproducible on latest Nightly 60.0a1 builds with Screenshots 29.0.0. So I think that the issue was introduced with the new Screenshots add-on version (29.0.0).

Also, I have managed to reproduce this issue on multiple websites, eg: imdb.com and cnn.com.

**Comment by johngruen** [comment] 2018-02-16 13:55
That's good to hear, that means we should be able to resolve w/o uplift. @6a68 would it be worthwhile to bisect nightly to figure out where this bug was introduced?

**Comment by SoftVision-CosminMuntean** [comment] 2018-02-19 12:20
It seems that this issue is reproducible on any website after Screenshots was used. It is enough just to activate then dismiss the Screenshots overlay and use the "Ctrl+C"/"Cmd+C" key shortcut.

In order to find when the bug was introduced I have used the Mozregression tool.. Here are the results:
Last good revision: 63ff291a2433f16ca847277564a011b68df5b9ac
First bad revision: db28301bc63b49419796cb999b679b99aee17f75
Pushlog: https://goo.gl/VH3dHb

It seems that [bug 1436218](https://bugzilla.mozilla.org/show_bug.cgi?id=1436218) introduced this issue, which is the update for Screenshots 29.0.0.

**Comment by SoftVision-CosminMuntean** [comment] 2018-02-23 10:46
@6a68 @ianb @johngruen 
Since we will release another version of Screenshots in Nightly, can we also fix this issue? The issue is reproducible on all websites and is very easy to be encountered.
Nightly goes to Beta 60 in March 12, code freeze starts on March 1st and if this will not be fixed by then, then we will have to do an uplift in Beta.

**Comment by chenba** [comment] 2018-02-23 15:13
I'll take a look at it today.

**Closed** 2018-02-23 23:16 UTC
Labels: defect, firefox

**Comment by SoftVision-CosminMuntean** [comment] 2018-02-27 10:12
I have retested this issue on the [Nightly try build](https://treeherder.mozilla.org/#/jobs?repo=try&revision=392fc70eefcdd1b94d7f802dc21d033e1bdc48f6&selectedJob=164057945) with Screenshots 30.0.0 version and also with Screenshots 31.0.0 dev version and the issue is no longer reproducible. Tested on Windows 7 x64, Mac 10.12 and Arch Linux.

@chenba thanks for fixing it!
