### ISSUE TITLE
"Copy Image Text" option from context menu is not localized

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2561] opened 2017-04-05 13:15 UTC
[Affected versions]:
- Firefox 55.0a1 (Build ID:20170404030204)
- Page Shot 6.0.7601

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Install or extract a German Nightly build for this issue.
- The "xpinstall.signatures.required" is set to "false" and latest Firefox Screenshots (6.0.7601) custom build is installed on a new clean profile.

[Steps to reproduce]:
1. Open the German Nightly build with the profile from prerequisites and navigate to any website.
2. Click the Firefox Screenshots button from browser toolbar. 
3. Perform a selection and save it.
4. Right click on the image and observe the context menu options.

[Expected result]:
- The "Copy Image Text" option is localized and is displayed in German like the other options.

[Actual result]:
- The "Copy Image Text" option is not localized, is displayed in English.

[Notes]:
- @ianb @clouserw , I have observed that the strings from "My Shots" page and saved shot details page are not yet localized. The strings from those pages will be localized?
- Here is a screen recording with the issue:
![copy image text](https://cloud.githubusercontent.com/assets/19226534/24707029/be649304-1a1a-11e7-95a8-0b7a2c9b1994.gif)

**Comment by johngruen** [comment] 2017-04-05 15:42
Good catch

**Comment by ianb** [comment] 2017-04-24 20:55
This string is in the server, though we can confirm that @6a68 is including it in his strings.

**Comment by johngruen** [comment] 2017-06-12 17:47
Closing as a dupe of Server l10n in general

**Closed by johngruen** 2017-06-12 17:47 UTC
