### ISSUE TITLE
Screenshots Throw a Haywire Error If Shot UI is Dismissed before Upload is Completed

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4887] opened 2018-09-13 18:31 UTC
#### Prerequisite 
Be on a slow network, or be fast with switching tabs, or upload a very large (in MB not pixels) image.  Or all three.

#### STR
1. Save a shot.  This will open a new tab.
1. Go back to the tab where you took the shot; the shot UI should still be on the page.
1. Dismiss the UI by clicking X.
1. Wait for the upload to complete.

#### Expected
No errors at least.

#### Actual
A "Screenshots has gone haywire..." error.  This is caused by the attempt to copy the shot url into the clipboard.

**Comment by SoftVision-CosminMuntean** [comment] 2018-09-14 07:57
I have added a similar behavrior in issue [#2996](https://github.com/mozilla-services/screenshots/issues/2996#issuecomment-319973728). But instead of clicking the "X" button I have clicked the "Save" button. It seems that the issue is also reproducible if you click the "Copy" or "Download".

However, I get the same error if I click any of the buttons.

**Comment by clouserw** [comment] 2018-09-17 15:55
duplicate of #2996

**Closed by clouserw** 2018-09-17 15:55 UTC
