### ISSUE TITLE
The string and the buttons are no longer localized in the supported languages, on the server side

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#5022] opened 2018-10-10 09:16 UTC
[Affected versions]:
- Nightly 64.0a1
- Screenshots 34.0.0 dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a German Nightly (64.0a1) build installed or extracted.
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set to "true".
- Have the Screenshots 34.0.0 dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile. 

[Steps to reproduce]:
1. Open the Firefox German build with the new profile from prerequisites and navigate to any website.
2. Save a selection on the page.
3. Observe all the tooltips, buttons and the strings.

[Expected result]:
- All the buttons and the strings are displayed in German.

[Actual results]:
- The buttons and the string are displayed in English.

[Notes]:
- The issue is also reproducible for other languages (eg: French, Italian, Spanish).
- The issue is also reproducible on Firefox English builds if you change the preffered language from "about:preferences#general" page at "Language and Appearrance " section.
- Here is a screen recording of the issue:
![localized](https://user-images.githubusercontent.com/19226534/46725780-91955600-cc85-11e8-89dc-3295d5fd5226.gif)

**Comment by punamdahiya** [comment] 2018-10-10 15:44
Regression caused due to #4994

**Comment by punamdahiya** [comment] 2018-10-10 18:15
Should be fixed with #4944 revert

**Closed by punamdahiya** 2018-10-10 18:15 UTC
Labels: [QA]:Blocker issue

**Comment by SoftVision-CosminMuntean** [comment] 2018-10-11 11:30
I have verified this issue on latest Screenshots 34.0.0 dev version and is no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Arch Linux 4.12.
