### ISSUE TITLE
 Firefox Screenshots crashes on page with long table

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#3567] opened 2017-09-29 15:39 UTC
From https://bugzilla.mozilla.org/show_bug.cgi?id=1404164 (screenshot attached there):

1. Go to https://appointments.uidai.gov.in/CenterSearch.aspx

2. Select the "Pin Code" radio button.

3. Enter an Indian pin code that results in a lengthy table, for example "110094".

4. Enter the correct "Verification Code" (CAPTCHA) and press "Search".

5. Scroll down to the bottom of the table/page.

6. Activate Firefox Screenshots and simply move the mouse cursor onto the blue row at the bottom of the table that contains the text "Copyright © 2010 UIDAI All Rights Reserved.This website is best viewed in 1366x768 screen resolution.", then wait for a while.

7. Eventually you get a wait cursor and then Firefox Screenshots crashes with an "Unresponsive script" error (see attached screenshot) and leaves its info message (including the smiley face with moving eyes) behind on the screen if you select "Stop script".

**Comment by GithubManoj** [comment] 2017-09-30 17:42
Just to add, by "lengthy table" in step 3 I meant a table returned by that site that is long enough to cause the page to scroll. A table that doesn't result in a scroll bar is not sufficient to cause the crash.

**Comment by 6a68** [comment] 2017-10-13 20:01
turns out this is a dupe of the dxr bug, which is also a table-related error. Closing in favor of #3314

**Closed by 6a68** 2017-10-13 20:01 UTC
Labels: Firefox
