### ISSUE TITLE
Push notifications not working in Nightly

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#3919] opened 2017-12-18 16:56 UTC
Can someone confirm this @SoftVision-CosminMuntean

**Comment by SoftVision-CosminMuntean** [comment] 2017-12-18 17:06
It seems that on Windows the push notifications are working, but not on Mac OS. Probably is a Nightly regression. I am checking it now.

**Comment by SoftVision-CosminMuntean** [comment] 2017-12-18 17:45
The issue is reproducible only on Mac Os. I haven't managed to reproduce this issue on Windows 7 x64 and Ubuntu 14.04 x64.

IT seems that is a Nightly regression. Using mozregresssion tools I have found the regression range. Here are the results:

Last good revision: 03aebc551f9da0dfbe383c39d2fcb2f2975eeecc
First bad revision: 8fd1d4a79a48211fb77a442a7ad38b7a78d720b1
Pushlog: https://goo.gl/xtHpAK
Looks like [bug 952453](https://bugzilla.mozilla.org/show_bug.cgi?id=952453) introduced this issue.

Here is a screenshot with browser console errors after clicking the "Save" button:
![mac os no system notification](https://user-images.githubusercontent.com/19226534/34119721-e63c93a0-e42b-11e7-93f5-fa14af958a6f.png)

Should we log this also on Bugzilla or this can be fixed on the Screenshots side.

**Comment by SoftVision-CosminMuntean** [comment] 2018-01-04 13:40
After more investigations, it seems that not only Screenshots is affected by this Nightly regression. The push notifications are also not working for any websites (eg: Facebook) or add-ons (eg: Tab notifier or SnoozeTabs) that use them.
However, I have logged a new issue on Bugzilla for this: https://bugzilla.mozilla.org/show_bug.cgi?id=1427996

**Comment by marniepw** [comment] 2018-01-16 16:46
FIxed latest Nightly.

**Closed by marniepw** 2018-01-16 16:46 UTC
Labels: defect, firefox
