### ISSUE TITLE
[Annotations] Certain locale files and elements from websites can be dragged and dropped inside the text box

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla-services/screenshots#4655] opened 2018-07-17 16:16 UTC
[Affected versions]:
- Nightly 63.0a1
- Dev Edition 62.0b8
- Release Unbranded

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set to "true".
- The "extensions.install.requireBuiltInCerts " boolean pref is set to "false"
- Have the Screenshots 33.1.0 dev version installed on a new clean profile.
- Have a saved shot link.
- Have a .jpg file saved on desktop.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from the prerequisites and navigate to the saved shot link.
2. Click the “Edit this image” button.
3. Click the "Add text" button.
4. Drag and drop the .jpg file inside the text box and observe what happens next.

[Expected result]:
- Nothing happens, the .jpg file cannot be dropped inside the text box
OR
- An error message or the prohibited icon is displayed and the .jpg file is not dropped inside the text box.

[Actual results]:
- The .jpg file is dropped and displayed inside the text box.

[Notes]:
- This issue is also reproducible with other files such as: .bmp, .nef, .gif.
- There's a strange behavior even when dragging and dropping files from websites to the text box. In this particular case, the text box is populated with text specific to the video and increases its height.
- Screen recording with the issue: 

![drag and drop ss](https://user-images.githubusercontent.com/26000308/42830972-c50c5024-89f5-11e8-830a-52e0144ea1ec.gif)

**Comment by johngruen** [comment] 2018-07-18 17:10
Let's just disable dropping content in

**Comment by punamdahiya** [comment] 2018-07-18 22:31
This issue should be fixed with merge of #4658 in master

**Closed by punamdahiya** 2018-07-18 22:31 UTC
Labels: P1, [QA]:Major issue

**Comment by Softvision-CristinaBadescu** [comment] 2018-07-19 12:21
The issue is no longer reproducible using the latest Firefox Screenshots dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on latest Nightly build 63.0a1. Verified on Windows 10 x64, Mac 10.13.5 and Arch Linux 4.12 (on Linux, the file name is displayed in the text box).
