### ISSUE TITLE
[Annotations] Create an interface to let users annotate shots 

### ISSUE THREAD

**Issue by youwenliang** [mozilla-services/screenshots#3112] opened 2017-07-12 09:08 UTC
We want to let people annotate shots base on this trello card:
https://trello.com/c/CuAhHAah/10-fss-10-annotate-shots-with-comments

Here's the first version of the annotation idea:
https://mozilla.invisionapp.com/share/CFCJMNDZU

@niharikak101 can start from here!

**Comment by niharikak101** [comment] 2017-07-12 09:19
@ianb and I talked about adding a highlighter tool. What do you think @youwenliang?

**Comment by youwenliang** [comment] 2017-07-12 10:48
@niharikak101  Sure! I do have a highlighter tool in the previous version but somehow I dropped it, I can add it back!

Also I have question about the implementation approach, is it possible that every annotation element (text, pen stroke, lines...etc) is a movable object?

**Comment by niharikak101** [comment] 2017-07-12 16:18
@youwenliang I'll have to look more into the implementation, but I think it's definitely possible!

**Comment by youwenliang** [comment] 2017-07-14 09:53
@niharikak101 Sounds good!

By the way here's an updated version for annotation:
https://mozilla.invisionapp.com/share/X6CL83SBP

**Comment by niharikak101** [comment] 2017-07-18 08:37
Can I get assets for this? @youwenliang

**Comment by youwenliang** [comment] 2017-07-24 06:14
@niharikak101 We are still working on the visual part, will share you the assets this week!

**Comment by ianb** [comment] 2017-07-27 15:24
For the first version to land:

- [ ] The canvas where the annotations take place should be the same size as the clip image
- [ ] Two tools: highlight tool and blackout tool / pen (one tool would also be fine)
- [ ] Save/Cancel (no undo)
- [ ] Save will upload the image to the server
- [ ] The image will overwrite the old clip image
- [ ] Basic visual design matches the designs provided

**Comment by youwenliang** [comment] 2017-07-28 06:20
@ianb What about cropping tool? Do we want to include that in our first version?

**Comment by ianb** [comment] 2017-07-28 17:30
I'd like to leave out cropping for the first version – the implementation of cropping is fairly different from the other two tools, and I'd like us to make this as easy to land as possible.

**Comment by niharikak101** [comment] 2017-07-31 15:46
@youwenliang For the first version, I will just need icons for the highlighter, pen and the edit icon on the shot page.

**Comment by youwenliang** [comment] 2017-08-01 09:56
@niharikak101 Here's the icons you need:
[Annotation.zip](https://github.com/mozilla-services/screenshots/files/1190192/Annotation.zip)

Thanks!

**Comment by chenba** [comment] 2018-01-08 14:43
Isn't this a duplicate of #1849?  At least the titles are identical.

**Closed** 2018-01-25 16:42 UTC
Labels: P2, enhancement
