### ISSUE TITLE
Copy to clipboard doesn't work

### ISSUE THREAD

**Issue by dCosminn** [mozilla-services/screenshots#3859] opened 2017-11-29 12:42 UTC
The copy to clipboard option doesn't work here, Windows 10 FCU and the latest Nightly.
I have webrender enabled, like the set “gfx.webrender.enabled” to true, set “gfx.webrender.blob-images”  to true,  “image.mem.shared” to true. 
Tried with Firefox in Safe Mode(all addons disabled) and still doesn't work.

If i click to save the shot it will automatically copy to clipboard using this format: https://screenshots.firefox.com/otgnn6djJsVjl9Q5/twitter.com

If i click on the copy icon it tells me bottom right that it was copied into the clipboard but there is no sign of uploading the shot and the clipboard is empty. 
Also it seems that it clears the clipboard, like if i had something in clipboard, after clicking on the copy icon the clipboard ends empty.

**Comment by wresuolc** [comment] 2017-11-29 16:49
If you reset the preferences (or use a fresh profile with defaults) does this still happen?

**Comment by dCosminn** [comment] 2017-11-29 17:36
Made a new profile and the issue still happens.

**Comment by chenba** [comment] 2017-11-29 17:51
I cannot reproduce this with the same versions of Windows and Firefox.  I think that "it clears the clipboard" means something is being copied into the clipboard (thus replacing the previous content).

@dCosminn What happens if you try to paste into Paint.NET?  Do you get an error?  An empty/transparent image?

**Comment by dCosminn** [comment] 2017-11-29 18:00
@chenba Yes, you are right. It doesn't clear the clipboard it just stores the image.
When i paste it into Paint i can see the screenshot i took..

**Comment by chenba** [comment] 2017-11-29 18:10
@dCosminn Excellent.  I'll close this issue.

**Closed by chenba** 2017-11-29 18:10 UTC
