### ISSUE TITLE
"sent screenshot into clipboard" feature and button

### ISSUE THREAD

**Issue by HappyPony** [mozilla-services/screenshots#3531] opened 2017-09-21 15:04 UTC
I suggest to implement feature and button for sent screenshot to clipboard.  An Button example http://www.iconarchive.com/show/beautiful-flat-one-color-icons-by-elegantthemes/clipboard-icon.html .

S. dummy screenshot 
![111](https://user-images.githubusercontent.com/3226308/30702878-6fd17fbe-9eee-11e7-83c3-b603fb8afb52.png)

S. also "Full Web Page Screenshots" https://addons.mozilla.org/en-US/firefox/addon/fireshot/ with "Sent to clipboard" feature

**Comment by wresuolc** [comment] 2017-09-21 15:40
duplicate of #3485

**Closed by wresuolc** 2017-09-21 15:40 UTC
