### ISSUE TITLE
Copying image link to clipboard doesn't work in new build-in screenshot function

### ISSUE THREAD

**Issue by dall2812** [mozilla-services/screenshots#3571] opened 2017-10-02 07:56 UTC
**Steps to reproduce:**
I took a screenshot with the new build-in screenshot tool, clicked on "Save" and got a notification that the link to the image has been copied to my clipboard.

**Actual results:**
The link has not been copied to my clipboard.

**Expected results:**
The link should have been copied to my clipboard.

**Comment by SoftVision-CosminMuntean** [comment] 2017-10-02 08:47
@dall2812 , thanks for reporting this!

On what version of Firefox did you encountered this issue and also on what OS? We have tracked this issue in #3130, but I haven't managed to reproduce it.

I have retest this issue now on latest Firefox (56.0) release, Beta 57.0b3 and latest Nightly (58.0a1) build using a new profile for each, but I haven't managed to reproduce it.

**Comment by dall2812** [comment] 2017-10-02 08:55
Hi,

User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:56.0)
Gecko/20100101 Firefox/56.0
Build ID: 20170926190823


2017-10-02 10:47 GMT+02:00 SoftVision-Muntean Cosmin <
notifications@github.com>:

**Comment by SoftVision-CosminMuntean** [comment] 2017-10-02 09:02
Probably the issue is reproducible after updating Firefox 55.0.3 release to Firefox 56.0 release. 
@dall2812 Did you had Screenshots enabled by default in Firefox 55.0.3 release? Or did you manually enabled Screenshots from "about:config" page?

**Comment by dall2812** [comment] 2017-10-02 09:15
No, I did not manually enable it. I tried it for the first time directly
after the update this morning.

2017-10-02 11:02 GMT+02:00 SoftVision-Muntean Cosmin <
notifications@github.com>:

**Comment by wresuolc** [comment] 2017-10-02 15:52
@dall2812 if you restart the browser, does it work again?  We're having some trouble reproducing this.  Thanks!

**Comment by dall2812** [comment] 2017-10-04 07:32
Unfortunately not :(

2017-10-02 17:52 GMT+02:00 Bizarro @clouserw (minimal permissions) <
notifications@github.com>:

**Comment by johngruen** [comment] 2017-10-31 16:27
@6a68 will find a dupe for this

**Comment by 6a68** [comment] 2017-10-31 16:30
Closing in favor of #3130

**Closed by 6a68** 2017-10-31 16:30 UTC
Labels: Firefox
