### ISSUE TITLE
Copy to clipboard and download functionalities are not working for large selections on certain websites

### ISSUE THREAD

**Issue by davethegr8** [mozilla-services/screenshots#4366] opened 2018-04-25 00:31 UTC
If I try to save a very long page (30000px ish - https://medium.com/s/story/the-mtg-color-wheel-c9700a7cf36d) screenshots completely falls over. Trying to download gives me the "haywire" error, copy to clipboard only saves about 13000px, and Save limits to the same size.

As an aside, the dev tools screenshot node doesn't work at all, with no errors but I'm not sure that uses the same functionality.

I use screenshots to long-term archive things I find interesting as links can change, content can disappear.

**Comment by SoftVision-CosminMuntean** [comment] 2018-04-25 12:49
@davethegr8 thanks for reporting this!

I have managed to reproduce this issue for large selections using the following STR:
1. Navigate to https://medium.com/s/story/the-mtg-color-wheel-c9700a7cf36d page.
2. Click the "Take a Screenshot" option from "Page Actions" menu.
3. Click the "Save full page" button from the top right corner of the page.
4. Click the "Copy" or "Download" button.
5. Observe the behavior.

[Expected Results]:
- The selection is successful copied to clipboard or downloaded.
 
[Actual Results]:
- A "Whoa! Firefox Screenshots went haywire" message error is displayed and the loading spinner is continuously displayed.

[Notes]:
- I have managed to reproduce this issue only on the following websites:
-https://medium.com/s/story/the-mtg-color-wheel-c9700a7cf36d
-https://9gag.com/
-https://la-cascade.io/
- The issue is reproducible on latest Firefox 59.0.2 release and also on latest Nightly 61.0a1 build.
- Managed to reproduce this on Windows 7 x64, Mac 10.13 and Ubuntu 14.04.
- Here is a screenshot with browser console errors:
![copy to clipboard for large pages](https://user-images.githubusercontent.com/19226534/39246507-746cec9c-489f-11e8-94f2-aece60fa8dcc.png)

- Here is a screen recording with the issue:
![screen recording](https://user-images.githubusercontent.com/19226534/39246595-b2ad35ca-489f-11e8-9f01-13dd3981e256.gif)

**Comment by SoftVision-CosminMuntean** [comment] 2018-04-25 13:50
I think I misunderstood the issue. Probably @davethegr8 encountered #3852 since he tried to save a selection larger than 30000px and in my case the "Copy to clipboard" and "Download" functionalities are not working on the mentioned pages for cut off images. 
However, it seems that on other large pages (eg: imgur) the functionalities are working as expected . So I think that this issue is different than #3852.

**Comment by davethegr8** [comment] 2018-04-25 16:38
Wow thanks for that great repro process. I was running out the door to work and didn't have time to go into more detail, but that pretty well sums up the issue.

It's probably related to #3852 at the very least, if not a duplicate, but the following happens when working on a 31k px page:

- download still throws the "haywire" error
- copy to clipboard crops to 10k px (expected?)
- save crops to 10k
- dev tools works as expected

**Comment by colaas** [comment] 2018-05-01 03:48
Are you sure dev tools screenshot works as expected? Over here on a long page it make the camera sound but no screenshot is saved. Screenshot tool goes haywire of course.

**Comment by SoftVision-CosminMuntean** [comment] 2018-05-02 08:46
@davethegr8 sorry for my late repose. 
> download still throws the "haywire" error

Probably you encounter issue  #3852 here.

> copy to clipboard crops to 10k px (expected?)

I don't think that this is expected. Do you try to copy to clipboard a selection larger than 32000 px? Also, on which pages are you encounter this issue? 

> save crops to 10k

This is intended, see  #3538 
> dev tools works as expected

Dev tools is another functionality of the browser, different than Firefox Screenshots. We are working only on Firefox Screenshots.


However, it seems that here we have two issues:
1. The issue described by @davethegr8, that looks like is duplicate of #3852. So if you have a selection larger the 3200 px, the Copy, Download and Save buttons are not working and a error is displayed.
2. Copy to clipboard and download functionalities are not working on certain pages for cut off images.

Considering this I will close this issue as dupe of #3852 and for my described issue I have logged a different one: #4390.

**Closed by SoftVision-CosminMuntean** 2018-05-02 08:46 UTC
