### ISSUE TITLE
After "Page Shot" migration the "Could not establish connection..." error is displayed, if a Screenshots page is restored after a browser restart

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2955] opened 2017-06-02 14:44 UTC
[Affected versions]:
- Nightly 55.0a1
- Sccreenshots 8.2.0

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have a Firefox version where Screenshots is not installed and create a new profile.
- Have the "Show you windows and tabs from last time" option set on "about:preferences" page in General section.
- Have Test Pilot and Page Shot installed on the created profile.

[Steps to reproduce]:
1. Start the Nightly try build with the profile from prerequisites.
2. Wait until the migration happens, then close the browser.
3. Reopen the browser and navigate to any website and save a selection.
4. Focus the saved screenshots details page and close the browser.
5. Reopen the browser and observe the behavior.

[Expected result]:
- No errors are displayed.

[Actual results]:
- "Could not establish connection. Receiving end does not exist." error is displayed.

[Notes]:
- Haven't managed to reproduce this issue on Mac OS.
- This issue is only reproducible if a Sccreenshots page is restored after a browser restart. If any of Screenshots page is not focused no errors are displayed after a restart.
- Here is a screen recording with the issue: https://goo.gl/KoClzk
- Here is a screenshot with browser console errors:
![connection](https://cloud.githubusercontent.com/assets/19226534/26730871/0194df8a-47bb-11e7-8381-9d209263d2ae.png)

**Comment by ianb** [comment] 2017-06-02 19:26
I think this is because sitehelper.js loads up and tries to talk to the background page, and the background page hasn't been initialized yet. It's a racy condition, so it's not surprising that it's hard to reproduce.

We can work around this, but maybe we should also report it as a WebExtension error.  I think the deferred initialization of background pages is meaning that they can be unloaded when a content_script starts, but I'm guessing that's not something WebExtension authors would expect.

**Comment by 6a68** [comment] 2017-06-09 18:55
@ianb Is there any reason we run the content scripts [early](https://github.com/mozilla-services/screenshots/blob/master/addon/webextension/manifest.json.template#L38)? The [default](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/content_scripts#run_at) is to wait till the background page's document has settled.

I'm working on reproducing the bug, suspect that going back to the default `run_at` value may fix it.

**Comment by ianb** [comment] 2017-06-09 19:07
I think we run it early for slightly better responsiveness, but if it's a fix then that could be changed.  But I think running it late is just like using a timer delay; it isn't the source of the problem, but it will probably fix the problem.

My thought on fixing this was just to implement a limited-time retry loop around the key call, catching the known error.

**Comment by 6a68** [comment] 2017-06-09 19:12
Yeah, catching the known error sounds like a good idea.

Given that we've had a variety of weird errors at startup, I wonder if it would make sense to just not ever show the error notification in the first ~15 seconds after the browser starts.

**Comment by 6a68** [comment] 2017-06-09 19:13
@SoftVision-CosminMuntean Thanks for the fantastic STR. I'm able to consistently reproduce this bug on my super old windows laptop :+1:

**Comment by ianb** [comment] 2017-06-09 19:14
I would also support suppressing popups, though I'm not sure how to tell when the browser starts up from sitehelper.js. Except I guess the errors actually are shown in senderror.js, and we could simply record the time the background page is loaded up.

**Comment by 6a68** [comment] 2017-06-09 22:06
I opened a pull request to fix this by waiting to load content scripts until the page has loaded.

@SoftVision-CosminMuntean Would you mind verifying the bug is fixed with this Try build? https://archive.mozilla.org/pub/firefox/try-builds/jhirsch@mozilla.com-6c4ddbc18cf0515f4282f4d0191c8daa8a8681b0/try-win64/

The Try build just includes the manifest change, not the change to suppress error messages on startup, so the error should still appear if the manifest change isn't enough.

**Comment by SoftVision-CosminMuntean** [comment] 2017-06-12 12:43
@6a68  I have retested this issue using the provided Nightly try build and is no longer reproducible. The "Could not establish connection..." error is no longer displayed.
Tested on Windows 7 x64 and Windows 10 x64.

**Closed** 2017-06-12 15:54 UTC
Labels: firefox-55
