### ISSUE TITLE
The Screenshots overlay is broken if the browser is maximized after a selection is performed

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#4510] opened 2018-05-30 16:37 UTC
[Affected versions]:
- Nightly 62.0a1, Build ID: 20180530100110

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the latest Nightly build and resize the browser.
2. Perform a selection.
3. Maximize the browser and observe the behavior.

[Expected result]:
- The Screenshots overlay is correctly displayed (except the performed selection).

[Actual results]:
- A lighter part appears on the Screenshots overlay in the right side.
 
[Notes]:
- This issue is not reproducible on older Nightly builds such as 61.0a1 (Build ID: 20180410220129) with Screenshots 30.1.0 version.
Considering this, I've managed to find a regression-window using the Mozregression tool. Here are the results:
Last good revision: 2a51222fb8239a736ddb8f8887d4fbc743434fab
First bad revision: 2fecadce382ec91078e46f2b86e0bef186728b9e
Pushlog: https://goo.gl/y13W6n
From the provided pushlog it seems that latest version of Screenshots 32.1.0 introduced this issue.

- Here is a screen recording of the issue:
![ss - broken overlay](https://user-images.githubusercontent.com/31244235/40734321-bc0c1b9c-6440-11e8-806b-889f62f7b528.gif)

**Comment by Softvision-CristinaBadescu** [comment] 2018-05-31 16:12
This issue is also reproducible if you resize the browser.

**Comment by 6a68** [comment] 2018-05-31 16:30
I suspect this regression was caused by #4258: the width of the right-side background div in the selection view is now fixed, but a resize listener wasn't added at that time.

**Closed** 2018-06-20 21:39 UTC
Labels: [QA]:Normal issue

**Comment by Softvision-CristinaBadescu** [comment] 2018-06-21 08:13
Thanks for fixing this! The issue is no longer reproducible using the latest Firefox Screenshots v33.0.0dev installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on latest Nightly build 62.0a1 (2018-06-20), on Windows 10 x64, Mac 10.13.5 and Arch Linux 4.12.
