### ISSUE TITLE
Look at new private browsing download support

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3274] opened 2017-08-04 18:28 UTC
The relevant bug ([Bug 1362448](https://bugzilla.mozilla.org/show_bug.cgi?id=1362448)) is landed, we should see how it helps.

**Comment by 6a68** [comment] 2017-10-18 19:27
See also #2818

**Comment by 6a68** [comment] 2017-10-18 19:28
Actually, I think this is a dupe of #2818. Closing

**Closed by 6a68** 2017-10-18 19:28 UTC
Labels: needs:product
