### ISSUE TITLE
There is not "grab Firefox's window too" option

### ISSUE THREAD

**Issue by myBestSoftAndPref** [mozilla-services/screenshots#1615] opened 2016-09-29 07:51 UTC
There is not "grab Firefox's **window** too" option.

This function **exist** in Firefox and available through developer's console (shift + F2) with

```
screenshot -chrome
```

command option.
It can be slightly confusing for silly users (most of users) but you can hide that option in pageshot's configuration.

**Comment by ianb** [comment] 2018-01-10 23:59
Duplicate of #119

**Closed by ianb** 2018-01-10 23:59 UTC
Labels: enhancement, needs:priority
