### ISSUE TITLE
Connect screenshots to other image hosting services?

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3427] opened 2017-08-29 05:08 UTC
Do we want this thing to potentially make money / provide user choice of (possibly multiple) image hosting services?

Or do we want to own the entire experience?

If it's the former, we could look into API integration with the top N services. I think this would be pretty straightforward: we already have OAuth-based auth code, we could proxy other sites' images into the My Shots page (or just redirect the 'my shots' link to some third-party site).

**Comment by johngruen** [comment] 2017-08-29 15:41
One of our big goals is to create mind share for Firefox and the server helps us do this. TL;DR we'd need to do this in a way that factors in the value we accrue from having our server.

**Comment by wresuolc** [comment] 2017-11-09 22:56
duplicate of #3685

**Closed by wresuolc** 2017-11-09 22:56 UTC
