### ISSUE TITLE
"My Shots" doesn't seem to work

### ISSUE THREAD

**Issue by saberworks** [mozilla-services/screenshots#3604] opened 2017-10-09 16:37 UTC
I have shared a couple of screenshots in other tickets (#3603 and #3602).  When I am on the screenshots page and I click "My Shots" the page shows an image and a message saying it's "Looking for your shots..."  After a few seconds it redirects me to the "tour" page here: https://screenshots.firefox.com/#tour

It never shows the shots I have uploaded.  I'm on firefox 56 on a mac.

**Comment by Softvision-CristinaBadescu** [comment] 2017-10-10 13:34
I have tested this issue on latest Firefox Release 56.0, Firefox DevEdition 57.0b6 and latest Nightly build 58.0a1 (10/10/2017) and could not reproduce it. After taking some screenshots, I could access "My shots" from the overlay buttons and from each shot preview page.

Can you please retest this using latest Nightly build (https://nightly.mozilla.org/) and report back the results? When doing this, please use a new clean Firefox profile, to eliminate custom settings as a possible cause (https://goo.gl/AR5o9d).

If the issue is still reproducible, please provide in a .txt document the data from "about:support" page. You can do this by navigating to "about:support" page and click on the "Copy text to clipboard" button.

**Comment by johngruen** [comment] 2017-10-11 15:58
@saberworks do you have 3rd party cookies disabled? If so could you try enabling them (briefly) to confirm whether this resolves your issue? Not saying that's a long term fix...just want to make sure we diagnose your issue correctly.

**Comment by wresuolc** [comment] 2017-10-13 15:52
duplicate of #3581

**Closed by wresuolc** 2017-10-13 15:52 UTC
