### ISSUE TITLE
Investigate impact of IndexedDB browser.storage

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#4534] opened 2018-06-07 15:51 UTC
With [Bug 1406181](https://bugzilla.mozilla.org/show_bug.cgi?id=1406181) the backend for browser.storage is moving from a simple JSON file in the profile (`browser-extension-data/screenshots@mozilla.org/storage.json`) to an IndexedDB (I'm not sure where this is stored).

It's important to us that the deviceId and secret are maintained, so we want to be sure that this change doesn't impact that. Some specific scenarios, given a version of Nightly with Bug 1406181, and a version of release or beta without that bug:

1. If you start Release, make a shot, start Nightly, does the shot show up in My Shots?
2. If you start Nightly, make a shot, start Release, does the shot show up in My Shots?

And... maybe other things? Luckily once deviceId is set, it shouldn't be changed, so the only case when it is lost is if the add-on believes it wasn't set in the first place. But if something happens that causes a change to deviceId, all of the shots in My Shots will appear gone, so we want to look for that specifically.

**Comment by SoftVision-CosminMuntean** [comment] 2018-06-11 13:48
I have started to verify the described scenarios, here are the results:

> If you start Release, make a shot, start Nightly, does the shot show up in My Shots?
If you start Nightly, make a shot, start Release, does the shot show up in My Shots?

In both cases all the saved shots are displayed in "My Shots" page. I have verified this on Windows 7 x64, Mac 10.13 and Arch Linux 4.12 with Firefox 60.0.2 release, Beta 61 and latest Nightly (62.0a1) build.

> And... maybe other things? Luckily once deviceId is set, it shouldn't be changed, so the only case when it is lost is if the add-on believes it wasn't set in the first place. But if something happens that causes a change to deviceId, all of the shots in My Shots will appear gone, so we want to look for that specifically.

@ianb I am not sure exactly how can I test this scenario. Can  you please give me an example of a scenario or more information about how can I test this?

**Comment by 6a68** [comment] 2018-06-21 15:51
I think going from Nightly back to Release is the main issue we had to worry about. Closing for now. @ianb if you think of specific edge cases to test, feel free to file or reopen

**Comment by SoftVision-CosminMuntean** [comment] 2018-07-06 13:39
Since the "extensions.webextensions.ExtensionStorageIDB.enabled" pref is set to "false" by default, I have retested multiple scenarios with the pref set to "true":

1. Start Nightly, change the pref to "true", restart the browser, make a shot, observe the shots from My Shots page:
- The saved shots are correctly saved and displayed.

2. Start Nightly, make a shot, change the pref to "true", restart the browser and make another shot, observe the shots from My Shots page:
- Both save shots are correctly saved and displayed. Also the "storage.local data successfully migrated to IDB Backend for "Firefox Screenshots"..." message is displayed in browser console.

3. Start Nightly, change the pref to "true", restart the browser and make a shot, close the browser and start the profile with Firefox Release, observe the shots from My Shots page.
- The Onboaring tour is redisplayed and the shot saved on the Nightly profile is not displayed in My Shots page. If I reopen the profile with Nightly, the shot is redisplayed.
- Here is a screen shot with browser console errors: https://goo.gl/gtAqF5

4. Start Nightly, make a shot, change the pref to "true", close the browser and start the profile with Firefox Release, observe the shots from My Shots page.
- The shot saved before changing the pref to "true" is correctly displayed in "My Shots" page. However, an error is still displayed in browser console: https://goo.gl/f8ekkF

5. Start Release, make a shot, start Nightly, change the pref to "true", restart the browser and observe the shots from My Shots page:
- The shot made on Firefox Release is correctly displayed in "My Shots" page on Nightly.

6. Start Release, make a shot, start Nightly, make a shot, change the pref to "true", restart the browser and observe the shots from My Shots page:
- Both saved shots are correctly displayed in "My Shots" page.


It seems that the shots that are saved after the "extensions.webextensions.ExtensionStorageIDB.enabled" pref is changed to "true" are no longer displayed in "My Shots" page if the profile is opened with Firefox Release. Also, the shots that are made on Firefox Release are not displayed in Nightly if the pref is set to "true". 
The issue is not reproducible if you open the Firefox Beta instead of Firefox Release.
I have logged this issue in #4602.

Please let me know if you need more testing with different scenarios.

**Comment by johngruen** [comment] 2018-07-11 15:57
@ianb will follow up

**Closed** 2018-07-19 15:54 UTC
