### ISSUE TITLE
Haywire error on a tall page

### ISSUE THREAD

**Issue by clouserw** [mozilla-services/screenshots#4925] opened 2018-09-20 15:59 UTC
Originally from #4922 this page is throwing a haywire message if you try to save it locally:  https://www.nytimes.com/interactive/2018/09/20/us/politics/russia-interference-election-trump-clinton.html

**Comment by chenba** [comment] 2018-09-20 16:01
This is a duplicate of #3852.

**Closed by chenba** 2018-09-20 16:01 UTC
