### ISSUE TITLE
[RTL] Add RTL support for screenshots.firefox.com

### ISSUE THREAD

**Issue by ItielMaN** [mozilla-services/screenshots#4261] opened 2018-03-23 14:23 UTC
Current state:
![](https://screenshotscdn.firefoxusercontent.com/images/592a934f-a005-480a-b58e-5dc8faa92526.png)

Suggested state with RTL fixes (not perfect but close to it):
![](https://screenshotscdn.firefoxusercontent.com/images/6932cb7a-a538-4e10-87ae-3f221bd26239.png)

Things done in the second image:
1. Text now has RTL direction
2. Images swapped place with their corresponding text

Things that remain to be done:
1. Fix the padding between the top 2 links ("Getting started" and "My shots")

**Comment by yehudab** [comment] 2018-10-11 17:00
Would like to give this a try if that’s OK.
Did some RTL fixes for older Firefox sites in the past ([example](https://bugzilla.mozilla.org/show_bug.cgi?id=580573)).
I think that the screenshots in the bug description are missing, but I can guess the general direction, so I’ll post some screenshots as I make progress.
Let me know if there are other aspects of this issue I should consider.

**Comment by ItielMaN** [comment] 2018-10-11 17:28
@yehudab See updated pics.

**Comment by yehudab** [comment] 2018-10-11 17:50
@ItielMaN Thanks!

**Comment by yehudab** [comment] 2018-10-12 11:47
Trying to outline my solution here, before jumping into the code.

It looks like there is a need to address 2 parts of the code:
First, adding `dir=rtl` to the `<html>` tag in case the language is Hebrew, Arabic, or Farsi.
Second, add CSS that fixes text alignment, floats, margins, etc.

The first part seems to be straight forward: I can add a new function called `getIsRtl()` to [l10n.js](https://github.com/mozilla-services/screenshots/blob/master/server/src/l10n.js), and call it from the [l10n middleware](https://github.com/mozilla-services/screenshots/blob/master/server/src/middleware/l10n.js). Then save the value on the `req` object. 
After that, `reactrender.render` will use this `isRtl` flag to add `dir=rtl` to the template.

CSS is more tricky, and I’ve been considering 4 approaches to it.

Option 1 - Add `[dir=rtl]` before the classes to override the ltr behavior. 
Example usage:

```
.some-class {
    left: 10px;
    padding: 5px 10px 5px 0;
    [dir=rtl] & {
        left: auto;
        right: 10px;
        padding-right: 0;
        padding-left: 10px;
    }
}
```

Option 2 -  Use a bidi-mixin library, such as [sass-bidi](https://www.npmjs.com/package/sass-bidi). Behind the scene, the mixin will create a code similar to the example in option 1.
Example usage:

```
.some-class {
    @include bidi-value(padding, 5px 10px 5px 0, 5px 0 5px 10px);
    @include bidi-prop(left, right, 10px);
}
```

Option 3 - Define a few global variables that will hold the words `left` and `right`, and use these inside the source SCSS files. Then generate a second CSS file for use with rtl languages, and for this file, reverse the definition. This approach is used by some layout frameworks, such as [zurb foundation](https://github.com/zurb/foundation-sites/blob/develop/assets/foundation-rtl.scss). 
Example usage:

```
.some-class {
    #{$left}: 10px;
    padding: 5px 0 5px 0;
    padding-#{$right}: 10px;
}
```

Option 4 - Use logical start/end properties and values. These have just landed in Chrome 69, so it might be a good choice for a site that mainly caters to Firefox users. Support of IE/Edge, as well as Safari (Mac and iOS) is [not expected](https://developer.mozilla.org/en-US/docs/Web/CSS/padding-block-end#Browser_compatibility) any time soon.
Example usage:

```
.some-class {
    start: 10px;
    padding: 5px 0 5px 0;
    padding-block-end: 10px;
}
```

My inclination is to use option 3. This is the approach we’ve taken in my jobby job, and it offers the best balance between code maintenance and browser support. I’d love to hear your thoughts as well.

**Comment by ItielMaN** [comment] 2018-10-12 12:03
@johngruen Can you please address Yehuda's question in the above comment? Thanks.

**Comment by yehudab** [comment] 2018-10-16 19:00
Just to clarify about the scope of work, the issue is not only with screenshots' home page, but also for the inner pages: "all shots" (for Firefox users) and a single page shot (for Firefox and non-Firefox users).
Adding some samples below of issues (screenshots show status after `dir="rtl"` is added to the `<html>`):

All shots (Logged in on Firefox):
-----------------------------------
Order of buttons in footer is reversed (correctly), but the heart icon stays in place.

![image](https://user-images.githubusercontent.com/633345/47039411-8dd56800-d18c-11e8-9a8b-e4877d484b2d.png)

Single shot (logged in):
-------------------------
Shot-title is not aligned with site URL. 
No space between the `time-diff` and `expire-info` spans.

![image](https://user-images.githubusercontent.com/633345/47039709-3c79a880-d18d-11e8-94af-d1d5b91d3480.png)

Not logged in:
----------------
Vertical separator that should be between the Firefox Screenshots logo and image-title is to the right of the logo, making it look like a very thin scrollbar.

![image](https://user-images.githubusercontent.com/633345/47040042-fa049b80-d18d-11e8-9d9a-92709fb14649.png)

**Comment by yehudab** [comment] 2018-10-18 17:46
After consulting the documentation and @ianb in the [chat](https://mozilla.logbot.info/screenshots/20181017), I’ve changed my mind a bit, and decided to use [CSS logical Properties](https://drafts.csswg.org/css-logical/) for the implementation. 
As the standard is stabilizing, I feel it will nice to have a project that showcases its advantages. 
As for other browsers, we can always add [a CSS post process](https://github.com/jonathantneal/postcss-logical) to get either a single or split CSS files that are supported in all browsers.

**Comment by yehudab** [comment] 2018-10-19 11:29
My initial work on this issue is ready.
You can see above the linked commit with the CSS changes.
I'm still not asking for a PR, because I also want to take care of non-Firefox and Chrome browsers, and that requires a CSS post-process to complete.

Attaching below some screenshots after these changes:
![image](https://user-images.githubusercontent.com/633345/47215664-f26e0e00-d3aa-11e8-8bc9-750994e6a947.png)

![image](https://user-images.githubusercontent.com/633345/47215707-17628100-d3ab-11e8-93f0-a32213e6a889.png)

![image](https://user-images.githubusercontent.com/633345/47215734-2d704180-d3ab-11e8-85fb-821844cce12e.png)

![image](https://user-images.githubusercontent.com/633345/47215770-44af2f00-d3ab-11e8-9836-d63eeece61aa.png)

**Comment by yehudab** [comment] 2018-10-19 16:07
Fixed also the page navigation area. 
Here I chose to switch the direction of the arrows, so that the left arrow will go to the next page, but I kept the `1 / 4` in LTR as it made more sense to me.

@ItielMaN, what do you think?

![image](https://user-images.githubusercontent.com/633345/47230084-f82b1a00-d3d1-11e8-923d-4b06bbcd9aca.png)

**Comment by yehudab** [comment] 2018-10-19 19:58
Pushed the final phase, which includes support for other non Firefox and Chrome browsers.
I ended up serving the same CSS files to all browsers, to make sure that we don't get anything broken in the build pipeline. 

The PR looks a bit overwhelming, but most of it is technical substitution of left/right properties with logical properties.

I'd love to get some feedback for it, and will be happy to fix anything that you don't like.

@ItielMaN 
While checking all the screens, I've found out there are many missing translations to Hebrew. Please let me know if you need help with these.

**Comment by ItielMaN** [comment] 2018-10-20 16:41
> ![image](https://user-images.githubusercontent.com/633345/47215707-17628100-d3ab-11e8-93f0-a32213e6a889.png)

Did you manage to fix the paddings here?


> @ItielMaN, what do you think?
> 
> ![image](https://user-images.githubusercontent.com/633345/47230084-f82b1a00-d3d1-11e8-923d-4b06bbcd9aca.png)

No complaints here :)


> @ItielMaN
> While checking all the screens, I've found out there are many missing translations to Hebrew. Please let me know if you need help with these.

Most of the missing translations you've noticed are awaiting approval:
https://pontoon.mozilla.org/he/firefox-screenshots/all-resources/
You can go ahead and suggest translations to the missings strings there, and to the other projects there.

**Comment by yehudab** [comment] 2018-10-20 18:01
> Did you manage to fix the paddings here?

Yes, as far as I know, all padding issues are fixed. Adding below full page screenshots for both shots index and single shot pages.

![screenshot_2018-10-20](https://user-images.githubusercontent.com/633345/47258911-2597c680-d4ab-11e8-84ad-6ccc99c92c7a.png)

![screenshot_2018-10-20 wikipedia](https://user-images.githubusercontent.com/633345/47258910-2597c680-d4ab-11e8-89eb-f10fb198f4a1.png)
 

> Most of the missing translations you've noticed are awaiting approval:

Do you know by whom?

> You can go ahead and suggest translations to the missings strings there, and to the other projects there.

Thanks, I'll do that.

**Comment by tomer** [comment] 2018-10-20 19:08
Hey @yehudab, nice to see you again! We miss you. ☺

**Comment by yehudab** [comment] 2018-10-21 19:42
@ItielMaN, @tomer 
Added the two missing Hebrew translations to the home page.
What are the next step in order to pull them into this repo?

@flodolo 
A question to you: In Hebrew, we need three options for plural times. E.g.: `[one] day ago`, `[two] days ago`, `[other] days ago`.
Is there a way to add this via pontoon, or does the English source need to change first in order to support that?
If you manually add the `[two] days ago` option to `locales/he/server.ftl` it works fine.
 
Example original:
![image](https://user-images.githubusercontent.com/633345/47271460-6282bc80-d582-11e8-8ac7-94c0897c544c.png)

Example correct:
![image](https://user-images.githubusercontent.com/633345/47271437-0f106e80-d582-11e8-9723-c7486c74f814.png)

**Closed** 2018-10-30 18:18 UTC
Labels: l10n
