### ISSUE TITLE
The "Take a Screenshot" option from context menu doesn't work in Presentation Mode (pdf file)

### ISSUE THREAD

**Issue by cbadau** [mozilla-services/screenshots#5063] opened 2018-10-23 13:24 UTC
[Affected versions]:
Firefox 64.0b3 (BuildId: 20181022150107).
Firefox 65.0a1 (BuildId: 20181023100120).
Firefox 63.0 (BuildId: 20181018182531).
Firefox 59.0.2 (BuildId: 20180323154952).
Firefox 56.0.2 

[Affected platforms]:
Windows 7 64bit.
macOS 10.13.
Ubuntu 16.04 32bit.

[Steps to reproduce]:
1. Launch Firefox.
2. Open a random PDF file [example](http://www23.statcan.gc.ca/imdb-bmdi/pub/instrument/3901_Q2_V3-eng.pdf). 
3. Click the Presentation Mode button.
4. Right click to open context menu and click on the "Take a Screenshot" option. 

[Expected result]:
The Screenshots overlay is displayed.

[Actual result]:
Nothing happens in Presentation Mode. The Screenshots overlay is displayed only after exiting from Presentation Mode. 

[Regression range]:
- It's not a regression since the issue is also reproduced in Firefox 56.0.2.

**Comment by 6a68** [comment] 2018-10-23 20:19
Screenshots doesn't work in fullscreen mode. As a workaround, if you exit presentation mode, you should be able to take a screenshot inside the PDF.js viewer that ships in Firefox 👍 

Dupe of #5064

**Closed by 6a68** 2018-10-23 20:19 UTC
