### ISSUE TITLE
Investigate "Attempted to call slides.display() twice"

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3512] opened 2017-09-19 17:32 UTC
This error occurs 10x more frequently in Sentry than any other error.

Not sure it has any user-visible impact.

https://sentry.prod.mozaws.net/operations/screenshots-addon-prod/issues/615778/

**Comment by johngruen** [comment] 2017-09-20 13:36
FWIW i take the tour a ton. Might be good to have @SoftVision-CosminMuntean to hammer on the tour to try to error it?

**Comment by SoftVision-CosminMuntean** [comment] 2017-09-20 13:43
@johngruen sure, I can investigate this.

**Comment by ianb** [comment] 2017-09-20 15:50
Note that the error will only show up in the Browser Console, it won't show up as a popup or failure.

**Comment by SoftVision-CosminMuntean** [comment] 2017-09-22 13:32
I have used the tour many times and tried multiple scenarios, but I haven't got any error is browser console.

Do you guys know on which Os, on what Firefox version or on what Screenshots version this error occurs more? Are these details shown in Sentry reports? I don't have access to it so any information could help to find some STR.

**Comment by johngruen** [comment] 2017-10-31 14:37
🤷‍♂️

**Comment by wresuolc** [comment] 2017-11-09 23:00
Duplicate of #2982

**Closed by wresuolc** 2017-11-09 23:00 UTC
