### ISSUE TITLE
"Saving your shot" page wrongly appears after clicking the "Back" button from the saved screenshot page

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#3995] opened 2018-01-22 09:52 UTC
[Notes]:
- For smaller saved screenshots the "Back" button is greyed out in most of the cases. This seems to be the expected behavior.
- This issue is also reproducible for the "Edit" screenshot page. Users might incline to select "Back" button or "Backspace" key in order to return to the saved screenshot page, without making any changes but they will be returned to the "Saving your shot" page.

[Affected versions]:
- Firefox 57.0.4 and up
- Screenshots 28.0.0 dev version, 25.0.0 and 19.2.0

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Have the "xpinstall.signatures.required" pref set to "false" and "extensions.legacy.enabled" pref set to "true".
- Have the latest Firefox Screenshots v28.0.0 installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html) on a new clean profile.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to a website.
2. Click the "Page actions" button and select "Take a Screenshot".
3. Perform a large selection and click the "Save" button.
4. Click the "Back" button and observe the behavior.

[Expected result]:
- The "Back" button is greyed out and unactionable.

[Actual result]:
- The "Back" button isn't greyed out and if you click it you are redirected to the "Saving your shot" page.

[Additional notes]:
- Here is a screen recording of this issue:
![back button - firefox screenshots](https://user-images.githubusercontent.com/31244235/35214549-2df7eb28-ff6a-11e7-9207-8ec4728319bb.gif)

**Comment by johngruen** [comment] 2018-01-23 16:47
I think this is a dupe, let's try to close this, but maybe @ianb could find the dupe. also, can't we wipe push state?

**Comment by chenba** [comment] 2018-01-24 22:18
This is caused by a race condition between `pushState()` in the `creating` page and the addon updating the tab's URL after the shot upload.  (It also makes the bug difficult to reproduce locally.)

I will create another issue with its own PR to follow this, because the fix in the addon needs to be released first.

**Closed** 2018-01-25 17:04 UTC
Labels: defect, firefox

**Comment by SoftVision-CosminMuntean** [comment] 2018-05-09 14:56
I have tested this issue on latest Nightly (62.0a1) build, latest Firefox Dev Edition (61.0b2) and Firefox Dev Edition (60.0b15) and the issue is no longer reproducible. After saving a shot, the "Back" button is greyed out and cannot be clicked.
Tested on Windows 7 x64, Mac 10.13 and Arch Linux.

I have also tried to test the behavior on Firefox versions lower then 60, but it seems that the Screenshots functionality is not present in the browser after installing [Screenshots dev version](https://screenshots.stage.mozaws.net/homepage/install-test-local.html). The add-on is displayed in "about:addons" page but it's not present in the browser.
In order to install Screenshtos dev version on Firefox 59 I have used an [unbranded build](https://wiki.mozilla.org/Add-ons/Extension_Signing#Unbranded_Builds) and also a Nightly 59.0a1 build. The behavior is the same on both version.
@6a68 @ianb @chenba  is there another way to install Screenshots dev version older Firefox versions <60? Or should I log this issue?

Here is a sscreenshot with browser console errors displayed after installing the Screenshtos dev version:
![browser console errors](https://user-images.githubusercontent.com/19226534/39821746-8fbfc6e6-53b1-11e8-86fd-7b1a31298002.png)

**Comment by chenba** [comment] 2018-05-09 21:48
@SoftVision-CosminMuntean It's because of https://github.com/mozilla-services/screenshots/commit/07b3b39 and [bug 1431533](https://bugzilla.mozilla.org/show_bug.cgi?id=1431533).  But you don't really need to run the dev version of the addon on older versions of Firefox.  What we need to test is using [older versions of the addon](https://github.com/mozilla-services/screenshots/releases) with the dev version of server.  Are you set up to build your own Screenshots addon?

**Comment by chenba** [comment] 2018-05-10 14:53
@SoftVision-CosminMuntean If you have the project already checked out and set up, try the following in Terminal from your project directory:

- Switch to a tag with `git checkout 19.1.0` (replace "19.1.0" with whichever version you want to test)
- Start the browser `./bin/run-addon -s https://screenshots.dev.mozaws.net`

If you have never checked out the project, then see if the README instructions make sense.  You can ignore the Postgresql stuff since you don't need to run the server.  I'd appreciate any feedback on that doc.

**Comment by Softvision-CristinaBadescu** [comment] 2018-05-11 12:48
I have tested the behavior by installing older versions of Firefox Screenshots.
The issue is still reproducible on older Firefox Screenshots versions, such as v19.2.0, v23.0.0, v25.0.0 and v28.1.0. If I correctly understood from [this comment](https://github.com/mozilla-services/screenshots/issues/4010#issuecomment-386379737), after encountering the issue, I should have been redirected to the shot page? If yes, this didn't happen and the "Saving your shot..." page remained displayed.

The issue is no longer reproducible using Firefox Screenshots v30.1.0, v31.3.0 and v32.1.0. After saving a shot, the "Back" button is greyed out and cannot be clicked.

Tested using the latest Nightly build 62.0a1 (Build ID: 20180510220127).
on Windows 10 x64, Mac 10.13.4 and Arch Linux 4.12.

Please let us know if you would like to test other Firefox Screenshots versions.

**Comment by chenba** [comment] 2018-05-11 16:44
@Softvision-CristinaBadescu Thanks for the thorough testing.

We definitely don't want anyone stuck on the "Saving your shot..." page.  I will revert #4011 for now  since I don't know why that is happening simply from looking at the code.

**Comment by Softvision-CristinaBadescu** [comment] 2018-05-14 08:38
@chenba , I think that the fix is really useful, especially for users that use the latest Firefox versions, since the issue is not reproducible starting with Firefox Screenshots v30.1.0 and up, which is already in the latest Firefox Release 60.0.

If we let this fix reverted, all users are affected. The "Back" button is actionable and the users are stuck on the "Saving your shot..." page.

The fix resolves the issue on current Firefox versions and only the users that use older versions (under 60) will be affected. If we look at the fuller part of the glass, I think that fix #4011 can improve the user experience.

**Comment by chenba** [comment] 2018-05-14 14:06
> If we let this fix reverted, all users are affected. The "Back" button is actionable and the users are stuck on the "Saving your shot..." page.

In order for the back button to be clickable, the user must be taken to shot page first.  In which case the user is not stuck on the "Saving your shot..." page.  And if the user does click back, then she can click forward go to the shot again.  Am I mistaken about that?  I'm trying to understand if there's a use case where the user is truly stuck.

**Comment by Softvision-CristinaBadescu** [comment] 2018-05-14 14:46
I don't remember for sure, when I tested the fix, if the "Forward" button was actionable because I was focused on the "Back" one and I also understood that I should have been automatically redirected to the saved shot page. Sorry for misunderstanding that! :)

What I know for sure is that now, after you click the "Back" button, the "Forward" one can not be actioned and we are stuck on the "Saving your shot..." page. Only if you reresh the page, you are redirected to the saved shot.

Here is a screen recording, hope it helps:
![ss - back button](https://user-images.githubusercontent.com/31244235/40004514-870f6466-579e-11e8-9c56-fcb7dc0dc337.gif)

**Comment by chenba** [comment] 2018-05-14 15:18
@Softvision-CristinaBadescu Thanks for the recording; it definitely helps.  Could you file a new bug with that recording and the STR?

**Comment by Softvision-CristinaBadescu** [comment] 2018-05-15 09:31
Sure thing :) I've logged it here #4451 .
