### ISSUE TITLE
[Annotations] "Color Picker" panel is no longer visible

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla-services/screenshots#4980] opened 2018-10-02 13:53 UTC
[Affected versions]:
- Nightly 64.0a1
- Screenshots 34.0.1374 dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set to "true".
- Have the Screenshots dev version installed on a new clean profile.
- Have a saved shot link.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to the saved shot link.
2. Click the "Edit This Image" button and click the "Crop" tool.
3. Click the "Color Picker" button.
4. Observe the "Color Picker" panel.

[Expected result]:
- The "Color Picker" panel is entirely visible.

[Actual results]:
- The "Color Picker" panel is opened under the background and is not entirely visible.

[Additional Notes]:
- The "Color Picker" panel is displayed when entering the "Add text" mode.
- Here is a screen recording with the issue:

![color picker](https://user-images.githubusercontent.com/26000308/46352777-42d33500-c663-11e8-8c56-3b7f4de974fd.gif)

**Comment by punamdahiya** [comment] 2018-10-02 17:11
Seems to be caused by overflow:hidden here https://github.com/mozilla-services/screenshots/blob/master/static/css/frame.scss#L419

**Comment by punamdahiya** [comment] 2018-10-12 19:01
Should be fixed by https://github.com/mozilla-services/screenshots/pull/5011

**Closed by punamdahiya** 2018-10-12 19:01 UTC
Labels: [QA]:Blocker issue

**Comment by SoftVision-CosminMuntean** [comment] 2018-10-15 08:51
I have verified this issue using the latest Screenshots (34.0.0) dev version and is no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Arch Linux.
