### ISSUE TITLE
Broken on "www.fupa.net"

### ISSUE THREAD

**Issue by sdfasdfgawe456h4356** [mozilla-services/screenshots#3595] opened 2017-10-03 22:17 UTC
Firefox 56.0 Windows 10

example link: https://www.fupa.net/berichte/sc-lahr-oliver-dewes-befreit-und-mit-leidenschaft-948068.html

Cant make PDF-screenshots on that website. Says download failed.

**Comment by 6a68** [comment] 2017-10-03 23:19
Hi! This is a duplicate of #3517, which will be fixed in Firefox 57. The quotation marks in the page title are illegal characters for a Windows filename.

As a workaround, you could save your screenshot to the cloud, then download the image from the screenshots site (right-click the image, then choose 'Save Image As...')

**Closed by 6a68** 2017-10-03 23:19 UTC
