### ISSUE TITLE
parallax image problem

### ISSUE THREAD

**Issue by alisiddique** [mozilla-services/screenshots#5044] opened 2018-10-16 07:36 UTC
Hi There,
Sometime can't capture parallax image website.
http://bridge201.qodeinteractive.com/
https://screenshots.firefox.com/vwXNVCdLzw0WEqDZ/bridge201.qodeinteractive.com

Thanks,
Ali

**Comment by marniepw** [comment] 2018-10-16 16:40
This is a duplicate of #2945. Parallax backgrounds don't always work due to the way we implement Screenshots.

**Closed by marniepw** 2018-10-16 16:40 UTC
