### ISSUE TITLE
Unclear how to create shots when non exist

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#4311] opened 2018-04-05 14:53 UTC
This is [from discourse](https://discourse.mozilla.org/t/how-to-create-a-shot-when-you-met-a-feature-ad/27396/1):

When no shots have been taken https://screenshots.firefox.com/shots says "No saved shots.  Go on, create some." but doesn't say how.  Maybe an option to see the introduction slides again would be good?

**Comment by chenba** [comment] 2018-04-05 15:04
Onboarding is in the addon... at the very least we should tell/show the user where to find the screenshots button (which should launch the onboarding).

**Comment by sevaan** [comment] 2018-04-05 15:43
Duplicate of #4179

**Closed by sevaan** 2018-04-05 15:43 UTC
