### ISSUE TITLE
[Annotations] The textbox can be wrongly moved out of view

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla-services/screenshots#4647] opened 2018-07-16 14:02 UTC
[Affected versions]:
- Nightly 63.0a1
- Dev Edition 62.0b7
- Release Unbranded

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
 - The "xpinstall.signatures.required" boolean pref is set to "false".
 - The "extensions.legacy.enabled" boolean pref is set to "true".
 - The "extensions.install.requireBuiltInCerts " boolean pref is set to "false".
 - Have the Screenshots 33.0.0 dev version installed from here, on a new clean profile.

[Steps to reproduce]:
1. Open the profile from prerequisites and navigate to a website (eg. www.wikipedia.com).
2. Take a screenshot and click the "Edit this image" button.
3. Click the "Add text" button.
4. Write a string of text and click on the textbox.
5. Drag the textbox to any of the outer limits of the screenshot and observe the behavior.

[Expected results]:
- The textbox remains inside the screenshot.

[Actual results]:
- The textbox moves outside the screenshot area and disappears from view.

[Notes]:
- I have attached a screencast of the issue:
![textbox](https://user-images.githubusercontent.com/40393891/42762820-fabe8b74-8919-11e8-9a5a-179ea6168e02.gif)

**Comment by Softvision-CristinaBadescu** [comment] 2018-07-23 11:34
This issue has been fixed by #4682. The issue is no longer reproducible using the latest Firefox Screenshots [dev version](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on latest Nightly build 63.0a1. Verified on Windows 10 x64, Mac 10.13.5 and Ubuntu 16.04 x64.

**Closed by Softvision-CristinaBadescu** 2018-07-23 11:34 UTC
Labels: [QA]:Normal issue
