### ISSUE TITLE
"TypeError: this.element is null" error is displayed, if a tab where Screenshots was used is focused and the browser resized

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3153] opened 2017-07-20 09:22 UTC
[Notes]:
- This issue is only reproducible on the Nightly try build with Screenshots v10.7.0.

[Affected versions]:
- Nightly 56.0a1
- Screenshots 10.7.0

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have the latest Nightly try build with Screenshots 10.7.0.
- The Screenshots onboarding tour was already visited.

[Steps to reproduce]:
1. Start the latest Nightly try and navigate to any website (eg. wikipedia.org).
2. Click the "Screenshots" icon from browser toolbar and save a selection.
3. Focused the tab from where the shot was saved and press the "F11" key.
5. Press the "F11" key again in order to return to the normal mode.
6. Resize the browser and observe the behavior.

[Expected result]:
- No errors are displayed.

[Actual results]:
- A "Who! Firefox Screenshots went haywire" error is displayed.

[Additional Notes]:
- I wasn't able to test this on Mac Os and Linux, because I haven't found any Nightly try build on the provided treeherder link for the specific Os's.
- Every time when the browser tab is focused and the window is resized the error is displayed.
- There are multiple scenarios in order to reproduce the issue, but with the provided steps, the issue is reproducible every time.
- Here is a screen recording with the issue: https://goo.gl/UoeDe6
- Here is a screenshot with browser console error:
![type](https://user-images.githubusercontent.com/19226534/28410216-a46b8f4c-6d45-11e7-9f11-9b2b44e6adf8.png)

**Comment by SoftVision-CosminMuntean** [comment] 2017-07-20 11:21
I have found a easy scenario in order to reproduce this issue:

[Prerequisites]:
- Have the latest Nightly try build with Screenshots 10.7.0.
- The Screenshots onboarding tour was already visited.

[Steps to reproduce]:
1. Start the latest Nightly try and navigate to any website (eg. wikipedia.org).
2. Click the "Screenshots" icon from browser toolbar and dismiss the overlay.
3. Resize the browser and observe the notification.

[Expected result]:
- No errors are displayed.

[Actual results]:
- A "Who! Firefox Screenshots went haywire" error is displayed.

[Notes]:
- Here is a screenshot with browser console error:
![this element is null](https://user-images.githubusercontent.com/19226534/28414873-134660da-6d56-11e7-9ee0-e4a3f7bb5bb0.png)
- Here is a screen recording with the issue: 
![errrorr resizing](https://user-images.githubusercontent.com/19226534/28415023-a9857a68-6d56-11e7-9827-9218841dd20f.gif)

**Comment by johngruen** [comment] 2017-07-20 11:30
I am able to reproduce this on dev

**Comment by wresuolc** [comment] 2017-07-20 12:13
I'm also able to reproduce this in Nightly.  This is a really user-facing bug and I don't think it ends until a restart -- it'll keep showing that message on every resize.  I don't think we can uplift with a bug like this, it makes us look too bad.  Let's fix it and regroup for the next beta.

An aside, but is there a reason we have this error message pop up like this?  Is there a scenario where it helps the user?  This is the second time we've had it getting triggered by something unrelated to interacting with Screenshots.

**Comment by 6a68** [comment] 2017-07-20 16:08
The error is only thrown if you make a selection in the page, then dismiss it, then resize.

The error does not occur:

- if you hit the toolbar button, then hit Escape without selecting a region in the page
- if you hit the toolbar button, then click 'save full page'

**Comment by 6a68** [comment] 2017-07-20 16:20
I did a git bisect, and the 10.6 commit looks like the culprit. Digging further

**Comment by 6a68** [comment] 2017-07-20 21:22
This is fixed in the `v10.4.0-export` branch

**Closed by 6a68** 2017-07-20 21:22 UTC
Labels: firefox-55
