### ISSUE TITLE
Unable to access shots or change timeout

### ISSUE THREAD

**Issue by emmyemi** [mozilla-services/screenshots#3292] opened 2017-08-09 00:42 UTC
Since this is similar to #2939, it _may_ be a dupe, but I thought I'd make a separate issue just to be safe since the conditions here are different.

Visiting the /shots page throws me into a reset loop. I'm unable to see my shots, and I'm also unable to change the amount of time for the screenshot to remain (the latter gives me [this error](https://i.imgur.com/oZceiGl.png) when I try). Unlike in #2939, the issue doesn't happen only in Containers or in Private Windows, but it happens across the entire browser.

If it means anything, I used the Test Pilot experiment before this feature was built into Firefox.

**Comment by emmyemi** [comment] 2017-08-09 17:59
@6a68 Nope, clicking that button sends me into a redirect loop as well. :/

**Comment by 6a68** [comment] 2017-08-09 18:13
@emmyemi OK, good to know. It's funny that you can create shots, but can't view 'my shots'.

Do you have third-party cookies enabled (Preferences > Privacy & Security > 'History' section)?

**Comment by emmyemi** [comment] 2017-08-09 21:33
@6a68 I do not. Due to privacy concerns I have that disabled by default, but turning it on just once to load the My Shots page seems to have fixed things on my end.

If third-party cookies are the issue, then perhaps it should be indicated in some way—though I'm not sure how.

**Comment by 6a68** [comment] 2017-08-09 21:47
@emmyemi I'm glad you were able to get it working! Closing as a dupe of #3085

**Closed by 6a68** 2017-08-09 21:47 UTC
