### ISSUE TITLE
[Annotations] The "Undo" option does not work after a string is pasted in the text box

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#4646] opened 2018-07-16 12:47 UTC
[Affected versions]:
- Nightly 63.0a1
- Dev Edition 62.0b8
- Release 61.0.1 Unbranded

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Firefox Screenshots v33.0.0dev installed.
- Have a saved shot link.
- Have a string copied to the clipboard.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to the saved shot link.
2. Click the "Edit this image" button and click the "Add text" button.
3. Right click the text box and select the "Paste" option.
4. Right click the text box and select the "Undo" option.
5. Observe the behavior.

[Expected result]:
- The pasted string is no longer displayed.

[Actual result]:
- The pasted string is still displayed.

[Notes]:
- This issue is also reproducible using the "Ctrl/Cmd + Z" keys combination.
- This issue is also reproducible if you use the "Ctrl/Cmd + V" keys combination to paste a string.
- This issue is not reproducible if you use the "Delete"/ "Cut" and then the "Undo" context menu options.
- This issue is not reproducible if you delete the text using the keyboard ( "Delete", "Backspace" or "Space" keys).
- Here is a screen recording with this issue:
![ss - undo option](https://user-images.githubusercontent.com/31244235/42759259-08f11eb0-890f-11e8-9825-d97b238aba50.gif)

**Comment by chenba** [comment] 2018-07-16 15:18
Probably caused by the change in paste handling from #4636.

**Comment by punamdahiya** [comment] 2018-07-17 18:23
Browser built-in undo stack for contenteditable elements is not very usable and is in review https://github.com/w3c/editing/issues/150

**Comment by punamdahiya** [comment] 2018-07-18 22:30
This issue should be fixed with merge of #4658 in master

**Closed by punamdahiya** 2018-07-18 22:30 UTC
Labels: P1, [QA]:Normal issue

**Comment by Softvision-CristinaBadescu** [comment] 2018-07-19 07:51
Thanks for fixing this! The issue is no longer reproducible using the latest Firefox Screenshots dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on latest Nightly build 63.0a1. Verified on Windows 10 x64, Mac 10.13.5 and Arch Linux 4.12.
