### ISSUE TITLE
Direct view images don't expire

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2195] opened 2017-02-22 20:56 UTC
Looking at the code, I don't believe direct view images expire when the shot page expires.

**Comment by wresuolc** [comment] 2017-03-06 23:40
This seems like a dupe of #2173

**Comment by ianb** [comment] 2017-03-06 23:41
This is for expiration, which happens at a different moment than expiration (due to the grace period).

**Closed** 2017-04-20 20:29 UTC
Labels: server
