### ISSUE TITLE
Full page screenshot doesn't work on G-Docs (and maybe others)

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#2830] opened 2017-05-09 16:51 UTC
It appears that on google docs, the height of the body element is set to the height of the window, and it's an internal element that handles document scrolling (`.kix-appview-editor`). Because of this, the full page screenshot functionality appears broken on G-Docs.

I would not be surprised if this breakage occurs on other sites on the web as well where the body is set to 100vh or overflow:hidden, and a child element handles document scrolling.

**Comment by ianb** [comment] 2017-05-09 17:02
Yes, any scrollable iframes can't be captured in full.  Google Analytics is another case.  There's no real solution, except to try to make the window itself appear to be very long and then rely on the iframe being stretched as a result.  Making the window larger would have all sorts of other unintended side-effects, and it's not clear what the right size would be.

I don't know how you'd make use of it, but printable stylesheets are an interesting workaround. If we force a print layout (e.g., open the developer CLI and do `media emulate print`) then we get the whole page.  Though in my testing the developer tools do something that is incompatible with the extension, so this doesn't actually work.

**Comment by ckprice** [comment] 2017-05-11 17:56
Hard to fix. Moving to stretch.

**Comment by ianb** [comment] 2017-06-09 18:35
I've encountered this in other contexts, and switching to a printable view was an effective solution. I'm not sure how we expose that, or document it, or if we can force a print media type.

**Comment by ianb** [comment] 2017-10-16 15:45
Duplicate of #3124

**Closed by ianb** 2017-10-16 15:45 UTC
