### ISSUE TITLE
Shots source disappeared after setting expiration date

### ISSUE THREAD

**Issue by youwenliang** [mozilla-services/screenshots#3504] opened 2017-09-18 10:38 UTC
As seen in this video:
![sep-18-2017 18-36-50](https://user-images.githubusercontent.com/8919308/30538401-6dce77f8-9ca0-11e7-876d-0300dde19e42.gif)

The source url disappeared after setting an expiration date, but reappeared if I click cancel when setting the expiration.

**Comment by wresuolc** [comment] 2017-09-18 15:41
The date on the server isn't matching the client.  This is a duplicate of #3255

**Closed by wresuolc** 2017-09-18 15:41 UTC
