### ISSUE TITLE
[Forums] A way to disable external website usage?

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/screenshots#2233] opened 2017-02-28 19:49 UTC
&mdash; via https://discourse.mozilla-community.org/t/a-way-to-disable-external-website-usage/13832

> **Shnoulle:** Page shot offer 2 solutions :
>
> - _Download:_ create the png file on tmp, allow to see it/save it on disk
> - _Save:_ save (must be upload) on an external website
>
> I like to see a new save : saving in data URI format on chrome://pageshot/content/picture.html HTML page (for example).
>
> Then : no need web access to see page shote, maybe add some tools :
>
> - copy data URI to clipboard
> - copy html img to clipboard
> - save img
> - upload img
>
> Then : it's the cleanest way to manage website screenshot.
> Currently : no real interest for me, OS have better tool.

---

> **fzzzy:** This is a good idea, but as Page Shot is designed to simplify sharing of content with others on the web, it may not be implemented in Page Shot itself. Instead, there is a possibility we may explore a new Experiment in Test Pilot which focuses on saving and organizing content locally for offline use and manipulation.

---

> **Shnoulle:** I use data URI in some of my project : cleanest way to share picture

---

> **fzzzy:** Yes, if you don't mind pasting a 900k data url, sure

**Comment by johngruen** [comment] 2017-09-12 16:52
I think this is a dupe of #2582

**Closed by johngruen** 2017-09-12 16:52 UTC
