### ISSUE TITLE
[Annotations] The text box is wrongly moved if a part of the string is selected and deleted

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#4644] opened 2018-07-16 12:13 UTC
[Affected versions]:
- Nightly 63.0a1
- Dev Edition 62.0b8
- Release 61.0.1 Unbranded

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Firefox Screenshots v33.0.0dev installed.
- Have a saved shot link.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to the saved shot link.
2. Click the "Edit this image" button and click the "Add text" button.
3. Type something and select a part of the string.
4. Press the "Delete" key and observe the behavior.

[Expected result]:
- The selected text is deleted and the text box does not move.

[Actual result]:
- The selected text is deleted but the text box is moved to the right.

[Notes]:
- This issue is also reproducible using the "Backspace" or "Space" keys.
- This issue is also reproducible using the "Delete" and "Cut" context menu options. 
- Here is a screen recording with this issue:
![ss - delete text](https://user-images.githubusercontent.com/31244235/43152422-2c7be72a-8f77-11e8-8ff5-0acf0299700a.gif)

**Comment by chenba** [comment] 2018-07-26 16:10
This issue is not on dev.  I think it was fixed in https://github.com/mozilla-services/screenshots/pull/4677

**Comment by chenba** [comment] 2018-07-26 16:24
Actually I think it's already shifted to the right at teh start, before any text deletion.

**Comment by chenba** [comment] 2018-07-26 16:31
I suspect that the center now is the center of the placeholder text added for #4681, and that isn't centered.

**Comment by punamdahiya** [comment] 2018-07-26 21:04
Expected result  about 'The selected text is deleted and the text box does not move.' hints the bug is about not moving textbox on deletion of character. 

We are moving textbox as characters are added and as  text width changes which is consistent with textbox moving on deletion. 

@Softvision-CristinaBadesc can you please help explain fix desired and should it be a bug or feature enhancement?

**Comment by Softvision-CristinaBadescu** [comment] 2018-07-27 08:22
@punamdahiya , sure thing! When I initially posted the issue, if you deleted the text using the context menu option, the text box position did not move. Indeed, the text box size is smaller, but it stayed in a fixed position.

Below you can see the screen recording with the original behavior, when the "Delete" context menu did not affect the text box position:
![delete](https://user-images.githubusercontent.com/31244235/43309913-cc372202-918e-11e8-9bbc-18bd32d316e7.gif)


Also, to explain better the desired behavior, I've used another addon (Awesome Screenshots Plus), and here you can see how the delete action does not affect the text box position:
![ss - awesome screenshots](https://user-images.githubusercontent.com/31244235/43309919-cfbd5180-918e-11e8-8a92-7fbfcca48aa5.gif)

Hope this helps to decide if this is a bug or an enhancement :)

**Comment by wresuolc** [comment] 2018-08-02 21:09
Since you can still move the text area around, we're considering this not a bug.

**Closed by wresuolc** 2018-08-02 21:09 UTC
Labels: [QA]:Minor issue, needs:product
