### ISSUE TITLE
native Windows toast notification shows blank / black image when screenshot copied to clipboard

### ISSUE THREAD

**Issue by asadotzler** [mozilla-services/screenshots#5029] opened 2018-10-11 18:41 UTC
Firefox recently moved from app-specific to native Windows notifications at https://bugzilla.mozilla.org/show_bug.cgi?id=1155505  These notifications have an icon/image next to the text but for Screenshots it shows a black square next to the Shot Copied text. I think this blank square should either be a Screenshots icon or a miniature view of the screenshotted content.

**Comment by ianb** [comment] 2018-10-15 15:54
We suspect this is a bug with the patch in Bug 1155505, we'll followup there.

**Comment by SoftVision-CosminMuntean** [comment] 2018-10-16 15:49
I have managed to reproduce this issue using latest Nightly  (64.0a1) build on Windows 10 x64. Also, it seems that there is a number code displayed under the description.
Here is a screenshot with the system notification:
![notification](https://user-images.githubusercontent.com/19226534/47029449-3cb97a00-d174-11e8-8786-9ef81bd3ec60.png)

**Comment by SoftVision-CosminMuntean** [comment] 2018-10-18 15:37
I have added a comment in[ bug 1155505](https://bugzilla.mozilla.org/show_bug.cgi?id=1155505#c75).
However, since this is a regression of bug 1155505, I have logged a new issue in Bugzilla with this behavior to be easier to track:  https://bugzilla.mozilla.org/show_bug.cgi?id=1500054

**Comment by punamdahiya** [comment] 2018-10-23 17:06
Closing as this issue is tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1155505

**Closed by punamdahiya** 2018-10-23 17:06 UTC
