### ISSUE TITLE
Investigate alien screenshots

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#4559] opened 2018-06-18 16:34 UTC
From discourse @ https://discourse.mozilla.org/t/alien-screenshots/29484 :

> Good afternoon. Sometimes I find in my pictures images that I certainly never saved. I do not imagine how it is possible. Do I have to worry about the security of my computer or my Firefox account?

**Comment by chenba** [comment] 2018-06-20 16:35
yarobofob on Discourse said that when it happens again, he'll give us an example.  He said that it doesn't happen often.

**Comment by 6a68** [comment] 2018-06-21 15:46
Let's close this for now

**Comment by chenba** [comment] 2018-06-22 13:51
We've confirmed that the image the user saved and the image the user did not save have the same deviceid.

**Comment by ianb** [comment] 2018-07-02 15:48
We don't have any reason to believe this is something other than a client-side confusion or error, and that the same device took both the shots. Closing since we can't reproduce and there doesn't seem to be anything actionable for us.

**Comment by robofob** [comment] 2018-08-19 23:49
I continue to see other people's screenshots, and my saved ones have disappeared. I'm the only computer user. I occasionally change my account password. Activity in the account is just mine, but miracles continue. I disabled the screenshots in the about:config, but sometimes I check. The same story!

**Comment by chenba** [comment] 2018-08-20 16:10
Hey @robofob, sorry to hear that.  Shots do expire if you do not change their expiration, so I think that's why your shots have disappeared.

As for seeing other people's shots, have you ever copied your Firefox profile to another computer?

For a last resort, you can try resetting your Firefox: https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings.  But keep in mind that will reset a good number of settings.  Please check that page for more info.

**Closed by chenba** 2018-08-20 16:10 UTC
Labels: [QA]:Invalid issue

**Comment by robofob** [comment] 2018-08-20 17:28
Hey chenba. I copied the profile from one computer to another on my computer. On both this account I use only me.
