### ISSUE TITLE
Annotation feature is hard to find if you don't use the site

### ISSUE THREAD

**Issue by wlach** [mozilla-services/screenshots#4806] opened 2018-08-22 17:14 UTC
I frequently use Firefox screenshots to clip a portion of the page to post in a github issue or chat client. I typically use the "copy" button after taking the shot, then paste it where needed. It seems like recent versions of screenshots got an annotation tool, which would be very useful for me (e.g. for calling attention to a particular part of a work-in-progress), however I wasn't aware of it until today, when I accidentally pressed "Save".

Suggestions (in order of a preference) to make this feature more discoverable and easy to use:

1. Decouple annotating a screenshot from saving it, so I can annotate a screenshot and then copy the result without needing to interact with the screenshots server (maybe there could be an option to save the annotated copy to the screenshots server).
2. Add an "annotate" button beside "Save" which saves the screenshot and opens up the annotation screen.

**Comment by chenba** [comment] 2018-08-22 18:38
@wlach Thanks for filing this issue.  I think it's a duplicate of #4795.

**Comment by wlach** [comment] 2018-08-22 19:11
Looks related at the very least :)

**Comment by ianb** [comment] 2019-02-07 21:12
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).

**Closed by ianb** 2019-02-07 21:12 UTC
Labels: server wontfix

**Comment by wlach** [comment] 2019-02-07 21:19
@ianb any chance we might implement this feature client-side only? that's really what this bug was about, rather than adding any particular server-side functionality.

**Comment by jellisii** [comment] 2019-07-16 17:57
Client side ability to add annotations to a screenshot would be nice.  Perhaps there's some functionality that can be borrowed from the print to file methods?
