### ISSUE TITLE
Favicons are 404ing on prod server

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3055] opened 2017-06-21 20:52 UTC
Note the empty favicon area:

<img width="300" src="https://screenshots.firefoxusercontent.com/images/95616c8c-7f7f-495b-916f-cebdce10063e.png">

https://screenshots.firefox.com/b9aRjDGImqhHvKgr/screenshots.firefox.com

Inspecting the page gives me this broken link to a favicon image:

https://screenshots.firefoxusercontent.com/proxy?url=http%3A%2F%2Fwww.cnn.com%2Ffavicon.ie9.ico&sig=pD58HTchR0evbk7TnksMrcuL6d0

which just gives an nginx 404 page. Maybe something's misconfigured?

**Comment by SoftVision-CosminMuntean** [comment] 2017-06-22 08:06
@6a68 I have logged a similar issue in #2648. This issue is also reproducible on "My Shots" page. The favicons are not displayed on save shots tiles.
You can find more information in the bug.

**Comment by wresuolc** [comment] 2017-06-22 15:41
thanks cosmin. closing as a dupe

**Closed by wresuolc** 2017-06-22 15:41 UTC
