### ISSUE TITLE
User Reports of Haywire error

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#3882] opened 2017-12-04 22:49 UTC
From Twitter. User reports error on "stock Firefox" and only for full-page/visible.

![image](https://user-images.githubusercontent.com/3323249/33580480-63c21960-d91b-11e7-9e72-fae51e8f05db.png)

**Comment by johngruen** [comment] 2017-12-04 22:51
@atoponce, if you're inclined, could you write in any console errors you see when you try to take a shot. Also, OS info would be useful to help diagnose. Thanks!

**Comment by atoponce** [comment] 2017-12-05 00:01
OS: Debian Sid (latest update as Dec 03, 2017)
Firefox: 57.0.1
Package: 57.0.1-1
Extensions:
* Awesome Screenshot - Capture, Annotate & More (as a fallback) 3.0.21
* Better TweetDeck 3.4.10
* bitwarden - Free Password Manager 1.22.0
* DuckDuckGo Plus 2017.11.30
* Make Trump Tweets Eight Again 1.1.2
* Privacy Pass 1.0
* Proxy Switcher and Manager 0.1.8
* Tree Style Tab 2.3.0
* uBlock Origin 1.14.20

Here is the stack trace from the JavaScript console:

    Unhandled error: 
    Error: Attempted makeEl before iframe was initialized
    Stack trace:
    makeEl@moz-extension://db9429c4-9fb0-428c-8bbf-e94d5538d824/selector/ui.js:52:13
    display@moz-extension://db9429c4-9fb0-428c-8bbf-e94d5538d824/selector/ui.js:711:17
    start@moz-extension://db9429c4-9fb0-428c-8bbf-e94d5538d824/selector/uicontrol.js:371:7
    setState@moz-extension://db9429c4-9fb0-428c-8bbf-e94d5538d824/selector/uicontrol.js:210:7
    onClickVisible@moz-extension://db9429c4-9fb0-428c-8bbf-e94d5538d824/selector/uicontrol.js:159:7
    assertIsTrusted/<@moz-extension://db9429c4-9fb0-428c-8bbf-e94d5538d824/assertIsTrusted.js:17:12
    watchFunction/this.catcher@moz-extension://db9429c4-9fb0-428c-8bbf-e94d5538d824/catcher.js:54:16
     undefined
    catcher.js:16:7

When taking either a full page or visible screenshot when in Safe Mode, it executes correctly. When running the browser normally, it crashes, and I can only take screenshots of selected regions.

I'll try taking screenshots with only one extension enabled at a time, and see if I can pin-point which extension is causing the crash.

**Comment by pascalchevrel** [comment] 2017-12-05 11:51
@atoponce can you paste here links to stack traces in about:crashes? Thanks

**Comment by 6a68** [comment] 2017-12-05 21:24
@atoponce The problem is the "Make Trump Tweets Eight Again" add-on, which overwrites the 'iframe.onload' listener for any iframe appended to any page. This breaks Screenshots (and probably some other sites, too). It's a closed-source add-on, so I'm not sure there's much else to do here.

Closing, thanks again for letting us know you were having problems.

**Closed by 6a68** 2017-12-05 21:24 UTC
