### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by rybarova** [mozilla-services/screenshots#3794] opened 2017-11-16 16:23 UTC
Hello is possible to add a shortcuts for this best tool? 
Example "Alt + Y" for screenshot full page and download in 1 step.  Thank you for your amazing tool.

**Comment by johngruen** [comment] 2017-11-16 16:49
We want to do this, but i'm going to close this as a dupe of #2491

**Closed by johngruen** 2017-11-16 16:49 UTC

**Comment by rybarova** [comment] 2017-11-16 16:54
Sorry for duplicate. I'm blind. I love your tool!!
