### ISSUE TITLE
Unable to change expiry time

### ISSUE THREAD

**Issue by Apply55gx** [mozilla-services/screenshots#3638] opened 2017-10-16 07:17 UTC
After creating a screenshot I'm unable to change the expiry time. When I try changing it following popup appears:
 
![screenshot](https://user-images.githubusercontent.com/17193640/31599367-68f6513e-b252-11e7-8bd0-6a2540b3bcfb.PNG)

Additionally the screenshot doesn't shows up under [my screenshots](https://screenshots.firefox.com/shots).

Even though it is very unlikely(only thing I block on screenshots.firefox.com is google analytics) I think it might be possible that this is caused by one of my addons. 

Addons I use:

-ublock
-https everywhere
-Cookie Autodelete
-Decentraleyes
-Disconnect
-Privacy badger (with google analytics blocked)

**Comment by johngruen** [comment] 2017-10-16 15:52
This is probably related to 3rd party something or other...

**Comment by johngruen** [comment] 2017-10-16 15:53
@Apply55gx do you disable 3rd party cookies?

**Comment by Apply55gx** [comment] 2017-10-17 05:59
Yes I disabled 3rd party cookies.

Tested it now with 3rd party cookies allowed and it worked.
Seems like that was the problem.

Should I leave this Issue open or close it(since its kind of resolved)?

**Comment by wresuolc** [comment] 2017-10-17 15:43
I'll mark it as a duplicate of #3581 .  Thanks!

**Closed by wresuolc** 2017-10-17 15:43 UTC
