### ISSUE TITLE
Possible to overwrite existing screens by visiting a page in browser history from pageshot.net/creating/...

### ISSUE THREAD

**Issue by thekyriarchy** [mozilla-services/screenshots#3132] opened 2017-07-14 16:58 UTC
This results in a null image, and breaks the entire "my shots" page in #3131

**Comment by 6a68** [comment] 2017-07-14 18:05
@thekyriarchy Thanks for filing this bug! Sorry you ran into that issue. We'll look into a workaround to get your shots back.

I wonder if we could fix this by removing the 'creating' pages from history? We might be able to do that by using `replaceState` instead of `pushState` [here](https://github.com/mozilla-services/screenshots/blob/master/server/src/pages/creating/controller.js#L9)

**Comment by 6a68** [comment] 2017-07-14 18:11
I'm not able to reproduce this using Screenshots:

1. Ensure Screenshots is enabled in Nightly (make sure `extensions.screenshots.system-disabled` is `false`)
2. Create any screenshot
3. Open a new tab
4. Go to the History menu > load the 'creating/' URL that should be two steps backward in history

Results:

5. The Creating page just shows a perma-spinner for me
6. My Shots still loads ok
7. The individual shot page still loads ok

I"ll try against pageshot.net with the old addon next

**Comment by 6a68** [comment] 2017-07-14 18:12
Doh! We graduated page shot, so I can't install the xpi any longer :-\

@ianb or @clouserw, could you send me a copy of the last signed pageshot xpi to test this?

**Comment by 6a68** [comment] 2017-07-14 18:27
Interestingly, on one of the affected pages, the `.clip-container` element is missing.

This suggests that `clip.image` was null: https://github.com/mozilla-services/screenshots/blob/e1f23807f0f0407c454bab43ee559cfa0f367083/server/src/pages/shot/view.js#L42

**Comment by thekyriarchy** [comment] 2017-07-14 19:01
it may have been a problem with an earlier version, as i can no longer reproduce, but my corrupted shots are all still missing.

**Comment by wresuolc** [comment] 2017-07-20 17:47
Thanks for filing.  I'll close this issue then.  Cheers

**Closed by wresuolc** 2017-07-20 17:47 UTC

**Comment by 6a68** [comment] 2017-07-20 20:28
@thekyriarchy We weren't able to figure out how to reproduce your issue. Please reopen if this happens again. Sorry that you lost some of your screenshots.

Also, if you are ever interested in contributing, feel free to grab any of the [good first bugs](https://github.com/mozilla-services/screenshots/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+bug%22). (Fixing any of those would qualify as the required 'small contribution' for an [Outreachy](https://gnome.org/outreachy/) internship application. Next round runs December-March, application period opens in September. Just sayin :-)

**Comment by 6a68** [comment] 2017-07-28 18:35
The fix for #3233 may explain what happened here

**Comment by thekyriarchy** [comment] 2017-07-28 18:50
ah, does this mean the images are permanently lost?

**Comment by 6a68** [comment] 2017-08-04 18:24
I think so, sadly
