### ISSUE TITLE
[10.10.0][Win8.1] Screenshot saving doesn't work on overclockers.ru, reddit and amazon

### ISSUE THREAD

**Issue by SXZ1** [mozilla-services/screenshots#2895] opened 2017-05-27 13:16 UTC
Hello!
I am using Nightly 27-05-17, Screenshot 6.6.0 has just got enabled by default. STR:

Create new profile, launch it, go to https://forums.overclockers.ru/viewtopic.php?p=14785630#p14785630
Press on the screenshot icon, select part of the page marked with red dots on this screenshot (you can do that by hovering the mouse under the nickname abdulla, I marked this place with green, and pressing left mouse button)
Screenshot is attached to this post, I also uploaded it to imgur: http://i.imgur.com/obi8PBE.png

Press on "Arrow down" (I guess that's download button)

ER: Screenshot is saved on disk
AR: Screenshot is not saved, error message in the lower right corner "Screenshot went haywhire.."
![image](https://cloud.githubusercontent.com/assets/26294581/26521700/88bbbfa6-42f7-11e7-9464-3e988f767433.png)

Also, see these comments for STR for reddit (two separate bugs):
https://github.com/mozilla-services/screenshots/issues/2895#issuecomment-305214862
https://github.com/mozilla-services/screenshots/issues/2895#issuecomment-305204315

**Comment by SoftVision-CosminMuntean** [comment] 2017-05-30 10:58
@SXZ1 Thanks for reporting this!

I have managed to reproduce this issue. It seems that any selection performed on "https://forums.overclockers.ru/viewtopic.php?p=14785630#p14785630" page, cannot be downloaded.

However, if the selection is saved, the download functionality from the "saved shot preview page" and also from "My Shots" page is working as expected.

Here is a screenshot with browser console errors:
![download selection](https://cloud.githubusercontent.com/assets/19226534/26576980/757e9bb4-4533-11e7-8560-06aa8e03896b.png)

**Comment by SXZ1** [comment] 2017-05-31 13:10
I can reproduce this bug in Nightly 31-05-17 and Screenshot 8.1.0. Changed the title.

**Comment by SoftVision-CosminMuntean** [comment] 2017-05-31 13:11
It seems that this issue is also reproducible on "https://www.reddit.com/" website.

**Comment by SXZ1** [comment] 2017-05-31 14:29
I can confirm that. STR:
Go to https://www.reddit.com/r/firefox/comments/6ef3jd/dropdown_menu_of_my_subreddit_wont_work_cant_use/
Click the red dot in order to select the following segment:
![image](https://cloud.githubusercontent.com/assets/26294581/26636796/75155804-4626-11e7-97b0-6ef5807a5339.png)
Press Arrow down

ER: Screenshot is saved
AR: Download starts but fails

I don't know if you should file a separate bug.

**Comment by SXZ1** [comment] 2017-05-31 15:02
Oops, STR from my previous comment is actually a separate bug! Here is STR for reddit front page:
Go to https://www.reddit.com/
Select the following segment
Press Arrow down
![image](https://cloud.githubusercontent.com/assets/26294581/26638629/3eb01f1a-462b-11e7-9de3-aaa518730fdd.png)

ER: Screenshot is saved
AR: Screenshot went...

**Comment by ianb** [comment] 2017-06-01 21:38
I'm not able to reproduce this in Nightly or from the repository master. The error appears from the browser console screenshot to be happening in the download process itself, which isn't something we've touched lately.

**Comment by SXZ1** [comment] 2017-06-02 07:04
I can still reproduce all three bugs (overclockers, reddit, reddit/r/firefox) in Nightly 01-06-17 with a new profile. Should I file a bug somewhere else?

**Comment by ianb** [comment] 2017-06-15 17:46
As [mentioned here](https://github.com/mozilla-services/screenshots/issues/3038#issuecomment-308817226) this is probably also related to #2981

**Comment by ianb** [comment] 2017-06-21 19:55
I haven't been able to reproduce this.  I came upon [this minor bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1375214), but it's not related.

**Comment by SXZ1** [comment] 2017-06-21 20:49
I can still reproduce the bug on overclockers.ru using str from the first post. Nightly 21-06-17, SC10.3.0
Screenshot from the browser console:
![image](https://user-images.githubusercontent.com/26294581/27405981-3c20cfee-56dc-11e7-8a4b-6bab4889ad53.png)

**Comment by SXZ1** [comment] 2017-06-21 20:52
I can also reproduce the bug from these two comments:
https://github.com/mozilla-services/screenshots/issues/2895#issuecomment-305214862
https://github.com/mozilla-services/screenshots/issues/2895#issuecomment-305204315

**Comment by ianb** [comment] 2017-06-21 21:11
I'm wondering if this is only a problem on Windows? It looks like the path handling is different there.

**Comment by SoftVision-CosminMuntean** [comment] 2017-06-22 14:42
> I'm wondering if this is only a problem on Windows? It looks like the path handling is different there.

@ianb it seems that this issue is reproducible only on Windows. I have tested this on Mac Os and Linux, and is not reproducible. The selection is successfully downloaded without any errors.

**Comment by SXZ1** [comment] 2017-06-26 19:14
Same problem on amazon. STR:
Go to https://www.amazon.com/Seiko-SSC509-PROSPEX-World-Leather/dp/B01JAEY0UW
Select the following part of the web page:
![image](https://user-images.githubusercontent.com/26294581/27556050-b9eefa2a-5abc-11e7-894f-cd7166f9d2f1.png)
Click Save

ER: Screenshot is saved
AR: Screenshot went haywire

Screenshot of the browser console below.

**Comment by SXZ1** [comment] 2017-06-26 19:14
![image](https://user-images.githubusercontent.com/26294581/27556087-dde12336-5abc-11e7-9a11-4d7f3e4e3f6a.png)

**Comment by SXZ1** [comment] 2017-07-17 12:04
Nightly 16-07-17, SC10.5.0, I can still reproduce bug from this comment:
https://github.com/mozilla-services/screenshots/issues/2895#issuecomment-305204315

**Comment by SXZ1** [comment] 2017-07-17 12:06
Browser console:
![image](https://user-images.githubusercontent.com/26294581/28267170-7da9b01e-6b01-11e7-8ee1-514d90e9bda6.png)

**Comment by wresuolc** [comment] 2017-08-01 16:58
@SoftVision-CosminMuntean is this still reproducible?

**Comment by SXZ1** [comment] 2017-08-01 17:07
Nightly 01-08-17, SC10.9.0. I can still reproduce bug from this comment:
https://github.com/mozilla-services/screenshots/issues/2895#issuecomment-305204315

**Comment by SoftVision-CosminMuntean** [comment] 2017-08-02 12:31
@wresuolc yes, is still reproducible on Windows with latest Nightly 56.0a1 build using the provided STR and [link ](https://www.reddit.com/r/firefox/comments/6ef3jd/dropdown_menu_of_my_subreddit_wont_work_cant_use/)by SXZ1.

I have also tested on Screenshots dev server and is still reproducible.

**Comment by SXZ1** [comment] 2017-08-02 15:37
@SoftVision-CosminMuntean thank you! One more URL where bug is reproduced: https://forum.palemoon.org/viewtopic.php?f=46&p=115732
Select any part of the page and press Download.

**Comment by SXZ1** [comment] 2017-08-07 19:00
One more link where bug is reproduced:
https://www.reddit.com/r/Amd/comments/6kcq4n/so_wtf_went_wrong_with_vega/
Browser console:
![image](https://user-images.githubusercontent.com/26294581/29041529-d993cc46-7bbb-11e7-89bb-61c6859a7fa7.png)

**Comment by lol768** [comment] 2018-09-07 18:39
Is this reproducible with a screenshot of something like:

```
<!doctype html>
<html>
  <head>
    <title>one:two</title>
  </head>
  <body>Hello world</body>
</html>
```

**Comment by SXZ1** [comment] 2018-09-07 19:09
It looks like I can't reproduce the bug any longer.

**Comment by chenba** [comment] 2018-09-07 22:17
@SXZ1 Thanks for verifying.  Closing the issue now.

**Closed by chenba** 2018-09-07 22:17 UTC
Labels: defect, firefox
