### ISSUE TITLE
Nightly startup error: registrationInfo is undefined

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#2927] opened 2017-05-30 18:58 UTC
Here's a bunch of errors found by @rnewman on nightly startup today:

```
------Error in promise: TypeError: registrationInfo is undefined
Stack trace:
exports.setDeviceInfoFromOldAddon@moz-extension://c97d1bb3-9395-1147-bb88-e20e86ba2bc8/background/auth.js:183:1
@moz-extension://c97d1bb3-9395-1147-bb88-e20e86ba2bc8/background/main.js:254:14
promise callback*this.main<@moz-extension://c97d1bb3-9395-1147-bb88-e20e86ba2bc8/background/main.js:248:24
@moz-extension://c97d1bb3-9395-1147-bb88-e20e86ba2bc8/background/main.js:6:14
  catcher.js:66:9
	watchPromise/< moz-extension://c97d1bb3-9395-1147-bb88-e20e86ba2bc8/catcher.js:66:9
	(Async: promise callback)
	watchPromise moz-extension://c97d1bb3-9395-1147-bb88-e20e86ba2bc8/catcher.js:61:12
	this.main< moz-extension://c97d1bb3-9395-1147-bb88-e20e86ba2bc8/background/main.js:248:3
	<anonymous> moz-extension://c97d1bb3-9395-1147-bb88-e20e86ba2bc8/background/main.js:6:14
exports.setDeviceInfoFromOldAddon@moz-extension://c97d1bb3-9395-1147-bb88-e20e86ba2bc8/background/auth.js:183:1
@moz-extension://c97d1bb3-9395-1147-bb88-e20e86ba2bc8/background/main.js:254:14
promise callback*this.main<@moz-extension://c97d1bb3-9395-1147-bb88-e20e86ba2bc8/background/main.js:248:24
@moz-extension://c97d1bb3-9395-1147-bb88-e20e86ba2bc8/background/main.js:6:14
  catcher.js:67:9
	watchPromise/< moz-extension://c97d1bb3-9395-1147-bb88-e20e86ba2bc8/catcher.js:67:9
	(Async: promise callback)
	watchPromise moz-extension://c97d1bb3-9395-1147-bb88-e20e86ba2bc8/catcher.js:61:12
	this.main< moz-extension://c97d1bb3-9395-1147-bb88-e20e86ba2bc8/background/main.js:248:3
	<anonymous> moz-extension://c97d1bb3-9395-1147-bb88-e20e86ba2bc8/background/main.js:6:14
Unhandled error: Object { fromMakeError: true, name: "TypeError", message: "TypeError: registrationInfo is unde…", stack: "exports.setDeviceInfoFromOldAddon@m…" } undefined  catcher.js:15:5
	exports.unhandled moz-extension://c97d1bb3-9395-1147-bb88-e20e86ba2bc8/catcher.js:15:5
	watchPromise/< moz-extension://c97d1bb3-9395-1147-bb88-e20e86ba2bc8/catcher.js:68:9
	(Async: promise callback)
	watchPromise moz-extension://c97d1bb3-9395-1147-bb88-e20e86ba2bc8/catcher.js:61:12
	this.main< moz-extension://c97d1bb3-9395-1147-bb88-e20e86ba2bc8/background/main.js:248:3
	<anonymous> moz-extension://c97d1bb3-9395-1147-bb88-e20e86ba2bc8/background/main.js:6:14
Telemetry disabled. Not sending critical error: Object { fromMakeError: true, name: "TypeError", message: "TypeError: registrationInfo is unde…", stack: "exports.setDeviceInfoFromOldAddon@m…" }  senderror.js:83:7
	exports.reportError moz-extension://c97d1bb3-9395-1147-bb88-e20e86ba2bc8/background/senderror.js:83:7
	<anonymous> moz-extension://c97d1bb3-9395-1147-bb88-e20e86ba2bc8/background/senderror.js:115:5
	exports.unhandled moz-extension://c97d1bb3-9395-1147-bb88-e20e86ba2bc8/catcher.js:20:7
	watchPromise/< moz-extension://c97d1bb3-9395-1147-bb88-e20e86ba2bc8/catcher.js:68:9
	(Async: promise callback)
	watchPromise moz-extension://c97d1bb3-9395-1147-bb88-e20e86ba2bc8/catcher.js:61:12
	this.main< moz-extension://c97d1bb3-9395-1147-bb88-e20e86ba2bc8/background/main.js:248:3
	<anonymous> moz-extension://c97d1bb3-9395-1147-bb88-e20e86ba2bc8/background/main.js:6:14

TypeError: subject is null[Learn More]  forms.js:243:15
Attempt to set a forbidden header was denied: Connection  1132911464-lcs_client_bin.js:92:385
Attempt to set a forbidden header was denied: Connection  rs=AHGWq9BiK0wZzDAvGknuEHRZ4FdjG3R50g:150:96
Attempt to set a forbidden header was denied: Connection  1132911464-lcs_client_bin.js:92:385
Attempt to set a forbidden header was denied: Connection  rs=AHGWq9BiK0wZzDAvGknuEHRZ4FdjG3R50g:150:96
Attempt to set a forbidden header was denied: Connection  1132911464-lcs_client_bin.js:92:385
```

**Comment by rnewman** [comment] 2017-05-31 14:08
Dupe of #2902, I think.

**Comment by wresuolc** [comment] 2017-05-31 18:31
thanks! 🍠

**Closed by wresuolc** 2017-05-31 18:31 UTC
