### ISSUE TITLE
Allow uploads to user choice of image hosts

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3227] opened 2017-07-27 15:55 UTC
To support arbitrary providers, we'd just need provider auth (via oauth?) and a provider API facade. Seems like the community should be able to offer such integrations via AMO.

How would the 'my shots' page work in such a case? Maybe we always upload to Mozilla, then track which sites you've shared out to? Or maybe we just send you to your, say, imgur profile page.

Could be a partner placement opportunity, too.

**Comment by ianb** [comment] 2017-07-27 15:57
#1614 is a request for imgur, and I'm pretty sure their API is dead-simple. We haven't moved much on it because engagement with the share panel is pretty low.

**Comment by wresuolc** [comment] 2017-07-28 15:44
mozillaonline was also looking for this

**Comment by wresuolc** [comment] 2017-11-09 22:47
I think this is a forward-dupe of #3685

**Closed by wresuolc** 2017-11-09 22:47 UTC
