### ISSUE TITLE
[FxA]: "Invalid OAuth parameter: client_id" error is displayed when you try to connect to an account

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3244] opened 2017-07-31 13:36 UTC
[Notes]:
- I am not sure if this is a known issue or is reproducible only on dev server.

[Affected versions]:
- Nightly 56.0a1
- Screenshots 12.0.4794

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pre is set to "false".
- Have a custom Screenshots dev build installed on a new Firefox profile.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and open a new tab.
2. Click the Screenshots icon from browser toolbar.
3. Click the "cogwheel" from the right corner of the page.
4. Click the "Connect" button.
5. Observe the browser behavior.

[Expected result]:
- You are redirected to the login page.

[Actual results]:
- You are redirected to a "Bad Request" page.

[Additional Notes]:
- Here is a screenshot with browser console errors:
![fxa](https://user-images.githubusercontent.com/19226534/28779919-8db7f580-760d-11e7-8645-464a794bb5ee.png)
- Here is a screen recording with the issue:
![fxa](https://user-images.githubusercontent.com/19226534/28779926-9429e9c8-760d-11e7-9fe2-7fd541f88bfc.gif)

**Comment by wresuolc** [comment] 2017-08-01 16:33
duplicate of #3246

**Closed by wresuolc** 2017-08-01 16:33 UTC
