### ISSUE TITLE
Screenshot saved to Downloads folder without asking for download location

### ISSUE THREAD

**Issue by GAJansen** [mozilla-services/screenshots#3488] opened 2017-09-13 07:47 UTC
User Agent: Mozilla/5.0 (X11; Linux i686; rv:57.0) Gecko/20100101 Firefox/57.0
Build ID: 20170912013600

**Steps to reproduce:**
- on any page, select 'take a screenshot'
- save a selection or full page
- select 'download'
- despite my general settings being 'Always ask you where to save files,' the screenshot is downloaded without asking for a download location
- use the 'downloads' icon to open the Download location, this is the default lacation: 'Downloads' folder

**Actual results:**
- took a screenshot
- selected 'download'
- despite my general settings being 'Always ask you where to save files,' the screenshot is downloaded without asking for a download location
- use the 'downloads' icon to open the Download location, this is the default lacation: 'Downloads' folder

**Expected results:**
after taking the screenshot and selecting 'download', a dialog should have been shown asking me where I want the download to be saved

Note: _I have reported  this issue on mozilla (https://bugzilla.mozilla.org/show_bug.cgi?id=1399013) and was asked to also file the issue here._

**Comment by johngruen** [comment] 2017-09-13 15:47
This is a dupe of #3420. We want to fix this btw

**Closed by johngruen** 2017-09-13 15:47 UTC
