### ISSUE TITLE
The Overlay limits an unwanted area

### ISSUE THREAD

**Issue by emilghittasv** [mozilla-services/screenshots#3172] opened 2017-07-21 07:51 UTC
[Affected versions]:
Firefox 55.0b11
Firefox Screenshots version: 10.5.0

[Affected platforms]:
Windows 10 64 bit
macOS 10.11.6
Ubuntu 16.04 64bit

[Steps to reproduce]:

1. Launch Firefox with a clean profile.
2. Enable Firefox Screenshots.
3. Open Firefox Screenshots.
4. Skip the Firefox Screenshots tutorial.
5. Access https://www.reddit.com/.
6. Drag over a post title.

[Expected result]:
The overlay limits the selected area.

[Actual result]:
The overlay is not positioned over the selected area.

[Additional notes]
Please note that his issue was not reproduced on Firefox Nightly (Firefox Screenshots v10.5.0 and v 10.7.0)
Also please note that this issue doesn't reproduce that easily on Windows and Mac Oses.

Please access the following link for further information: https://goo.gl/Sq419C

**Comment by johngruen** [comment] 2017-07-24 11:41
I am unable to reproduce this on 10.8

**Comment by emilghittasv** [comment] 2017-07-25 07:57
Hi @johngruen  !

Unfortunately, I managed to reproduce this issue on Firefox 55.0b12 (Firefox Screenshots v 10.8.0) on Windows 10 64 bit.

![10 8 0](https://user-images.githubusercontent.com/28087895/28561685-05f4a3a8-7128-11e7-81d7-9177183c54b1.gif)

**Comment by SoftVision-CosminMuntean** [comment] 2017-07-25 12:06
I have managed to reproduce this issue on Beta 55.0b12, but not on latest Nightly (56.0a1) build. Based on this I have performed a "--find-fix" regression using the mozregression tools. 
It seems that the issue is reproducible on Nightly 54.0a1 build from 2017-03-01, but is not reproducible on Nightly 54.0a1 build from 2017-03-02. 

Here are the final results after using the mozregression tools:
- First good revision: 5ef0e255799d58592fbb7f70636cbb91c8b90c6a
- Last bad revision: e297bafab4ae9d6320bff24d9aa02202c1a33e10
- Pushlog: https://goo.gl/u2qneG

Theoretically one of the fixed bugs from the pushlog also fixed this Screenshots issue. The strange thing is that all of them were fixed in Nightly 54.0a1, but the Screenshots issue is still reproducible on Beta 55 and also on Firefox Release 54.0.1. 
I have used the mozregression twice and I got the same results. Probably the regression range is not correct?
@lizzard do you have any thoughts on this? 

cc @ianb @6a68

**Closed** 2018-01-18 16:55 UTC
Labels: defect
