### ISSUE TITLE
"Share" and "Flag" buttons from the saved shot page preview are not working on Edge browser

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla-services/screenshots#2935] opened 2017-05-31 12:20 UTC
[Affected versions]:
- Microsoft Edge 38.14393.1066.0
- Screenshots 8.2.1970

[Affected Platforms]:
- All Windows

[Steps to reproduce]:
1. Open Edge browser.
2. Navigate to a someone else's shot (https://screenshots.dev.mozaws.net/Uehl0P90TGlR08jh/ro.pinterest.com).
3. Observe the way the image is loaded and displayed.
4. Click on the "Flag" button and observe what happens next.
5. Click on the "Share" button and observe what happens next.

[Expected result]:
3. The saved shot image is loaded and correctly displayed in the center of the page. 
4. The mail client is opened in order to report the shot.
5. The "Share" pop-up is opened.

[Actual result]:
3. Only part of a stuck spinner is displayed.
4. The mail client is not opened.
5. The "Share" pop-up is not opened.

[Notes]:
- Please see the following screencast:
![edge](https://cloud.githubusercontent.com/assets/26000308/26631513/003291bc-4614-11e7-9949-2a79fe972468.gif)

**Comment by SoftVision-CarmenFat** [comment] 2017-08-07 14:03
Retested this issue today and here are the results:
- the image is now loaded and correctly displayed, the stuck spinner is no longer shown when opening someone's else's shot;
- still, the issues mentioned at steps 4&5 are still reproducible, nothing happens when clicking the "Flag" and "Share" buttons.

Reopening this issue due to the fact that "Flag" and "Share" buttons are clickable, but not actionable.

**Comment by 6a68** [comment] 2017-08-08 23:54
@SoftVision-CarmenFat I'm seeing expected behavior with the 'flag' and 'share' buttons on dev for the link in the description(https://screenshots.dev.mozaws.net/Uehl0P90TGlR08jh/ro.pinterest.com).

Would you mind taking another look? If you're still seeing problems, could you give details on the exact versions of windows and edge?

**Comment by SoftVision-CarmenFat** [comment] 2017-08-09 09:15
@6a68
Tested this again on multiple versions of Edge and here are the results:
- on older versions (25.10586.672.0 and 38.14393.1066.0), this issue is still reproducible;
- on the latest version (40.15063.0.0), this is **fixed**: the buttons work as expected.

Tested on Windows 10 Pro x64 bit.

**Comment by johngruen** [comment] 2017-08-09 11:53
Note that metrics suggests that these buttons are not widely used.

**Comment by 6a68** [comment] 2017-08-09 21:12
@johngruen Cool, I'm fine to wontfix this. Does legal need us to have a working 'flag' button?

**Comment by johngruen** [comment] 2017-08-24 20:55
Not sure we can backfill this, i'll test again and close when #3403 lands

**Comment by 6a68** [comment] 2017-08-31 22:51
@johngruen 3403 landed, good to close?

**Comment by johngruen** [comment] 2017-09-01 15:41
Wontfix due to meh

**Closed by johngruen** 2017-09-01 15:41 UTC
