### ISSUE TITLE
Delete this shot: not effective for one of my Firefox profiles

### ISSUE THREAD

**Issue by grahamperrin** [mozilla-services/screenshots#3480] opened 2017-09-10 04:10 UTC
<https://screenshots.firefox.com/KOZJaOkLUCntFpJI/screenshots.firefox.com> was shot with a heavily extended Firefox 55.0.3 (64-bit) on FreeBSD. 

My first attempt to delete the item was made _without_ cancelling the 'How long should this shot be retained?' prompt. Probably within five minutes of uploading the shot. 

I made a few subsequent attempts, both whilst viewing the item and with the overview at <https://screenshots.firefox.com/shots>. 

There's no visible error, but the attempts to delete have not succeeded; it's still there, from _22⁩ minutes ago_.

## Environment

```text
[grahamperrin@momh167-gjp4-hpelitebook8570p-freebsd] ~% date ; uptime ; uname -v
Sun 10 Sep 2017 05:02:58 BST
 5:02a.m.  up 1 day,  8:53, 4 users, load averages: 0.86, 0.99, 1.23
FreeBSD 12.0-CURRENT #0 r320869: Mon Jul 10 13:57:55 UTC 2017     root@releng3.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC 
[grahamperrin@momh167-gjp4-hpelitebook8570p-freebsd] ~% pkg info firefox | grep -i version
Version        : 55.0.3_1,1
[grahamperrin@momh167-gjp4-hpelitebook8570p-freebsd] ~% 
```

- [2017-09-10 05:07 about:support.txt](https://github.com/mozilla-services/screenshots/files/1290249/2017-09-10.05.07.about.support.txt)
- [2017-09-10 05:07 about:support raw.txt](https://github.com/mozilla-services/screenshots/files/1290250/2017-09-10.05.07.about.support.raw.txt)

**Comment by ianb** [comment] 2017-09-11 19:36
@grahamperrin: let me see if I understand the issue:

1. You created a shot
2. On the shot page you clicked on the expiration time, so you could edit it (but you didn't edit it)
3. Then you clicked the delete button
4. And presumably you confirmed the delete? (There's should be an OK/Cancel popup)
5. And the shot wasn't deleted

Is that the case?

**Comment by grahamperrin** [comment] 2017-09-11 20:49
Exactly. 

With the profile that I used to upload the shot, I still can't delete that shot. The same problem with a second shot that I uploaded. 

----

No comparable problem when I use a different profile, that currently has no extensions enabled. Incidentally it surprised me that shots seem to be profile-specific (I previously assumed that they were associated to my Firefox account).

**Comment by ianb** [comment] 2017-09-12 15:52
I think I see an error in our logs that might be related: [https://sentry.prod.mozaws.net/operations/pageshot-prod/issues/647377/](report here) (note: private except to Mozilla)

Except that's the client-side, which is unhelpful, probably the server side is [this report](https://sentry.prod.mozaws.net/operations/pageshot-prod/issues/355137/) which is just "Attempt to delete shot without login" (which has been producing 500s until probably our last deploy).

That the error happened on one profile but not another makes this seem likely – something about the one profile is keeping the authentication from working. Maybe a different cookie setting? Or a corrupt cookie that's getting in the way of the good authentication cookie?

**Comment by grahamperrin** [comment] 2017-09-12 19:19
I removed all `screenshots.firefox.com` cookies, still the shots are not deleted after I confirm deletion. 

An extension conflict, maybe?

**Comment by ianb** [comment] 2017-10-09 16:10
@grahamperrin : do you have third party cookies disabled? We've come to realize this is the pattern for most people who have this problem. We're fixing that in #3581

**Comment by ianb** [comment] 2017-10-12 17:42
I think this has been fixed by #3581

**Closed by ianb** 2017-10-12 17:42 UTC

**Comment by grahamperrin** [comment] 2017-10-17 19:21
> do you have third party cookies disabled? … 

No: 

![2017-10-17 20 20 08](https://user-images.githubusercontent.com/192271/31684761-b1646830-b378-11e7-97c9-8e97aa740f51.png)

**Comment by SoftVision-CosminMuntean** [comment] 2017-10-19 11:23
@grahamperrin can you please provide the list with all your installed add-ons? I want to do some tests to see if an add-on is in conflict with Screenshots and cause this issue. Probably an add-on that has something to do with cookies.

You can find the complete list of the installed extensions in "about:support" page at "Extensions" section or on "about:addons" page.

**Comment by SoftVision-CosminMuntean** [comment] 2017-10-19 14:43
Oh, sorry, I didn't noticed that you already provided the "about:support" page in the first comment. 
I have installed a few add-ons and I have observed that if you install the "mHeaderControl" add-on you can block cookies. I can reproduce the issue using this add-on with certain configuration of it.
@grahamperrin can you please disable the add-on and try again to reproduce the issue? 

If the issue is still reproducible, can you please also test this in Safe Mode? In this way you will have all the add-on disabled and we can figure out if an add-on is in conflict with Screenshots.

**Comment by grahamperrin** [comment] 2017-10-26 09:35
Thanks! 

Today I re-enabled mHeaderControl, with the following in its `storage.js`: 

```text
{"page_about:addons":{"prevent-caching":true},"page_github.com":{"prevent-caching":true}}
```

I can not reproduce the issue. Honestly I don't ever recall using it for any cookie (for me its prime purpose was one of a number of desperate attempts, over the years, to work around 2011 Mozilla bug [706970 - Tabs restored at startup (app tabs, session restore) should be refreshed from server, not in a "stale" state from cache](https://bugzilla.mozilla.org/show_bug.cgi?id=706970)), so I **doubt that mHeaderControl was the issue**. 

Side note (taking care to not create a cross-reference): 

- `https://github.com/maheee/mHeaderControl/issues/1` (open) is _preference for the required domain wrongly applied to other domains · Issue `#1` · maheee/mHeaderControl_

## Other possibilities

### Disconnect

https://addons.mozilla.org/addon/disconnect/reviews/912765/ (2017-08-30) reminds me that I was [repeatedly confused](https://twitter.com/grahamperrin/status/902803654847201280) ;-) by the GUI of Disconnect, but we have `"isActive": false` in the attachment to opening post, so **I don't suspect Disconnect**. 

### [ClearURLs](https://addons.mozilla.org/addon/clearurls/)

Whilst I don't associate it with cookies, I do associate with e.g.: 

- `https://github.com/KevinRoebert/ClearUrls/issues/6` – _ClearURLs 1.1.2.4 versus Google authentication for various non-Google services: error 400, invalid_request, missing required parameter: client_id · Issue `#6` · KevinRoebert/ClearUrls_ (supposedly fixed but I can not confirm the fix)

– and just for fun, as a side note, here's [today's twelve-day-old staleness in the Firefox view of that page](https://screenshots.firefox.com/iAECFITfpN2FYGsX/github.com) ;-)

It's enabled, but its filters are off at the time of writing. Yeah, I usually forget to switch it back on. I'm gonna post this comment, switch its filters on then tell whether this issue 3480 is reproducible …

**Comment by grahamperrin** [comment] 2017-10-26 09:52
… posted, then I closed then reopened this tab and (deep 2011-esque sigh) there was [the repeat of the draft of what I had posted](https://screenshots.firefox.com/XCA9UTPq4PKt9hFk/github.com) so I clicked the stale text and <kbd>Control</kbd>-<kbd>A</kbd><kbd>Delete</kbd> <kbd>Control</kbd>-<kbd>F5</kbd>, then with ClearURLs filters enabled I took another shot of part of this page and finally deleted that one without difficulty. So **I don't suspect ClearURLs**. 

----

As the bug is not reproducible at this time, I'm happy to leave this issue as closed. If it recurs, I'll revisit 👍 

Here, for reference only, is today's most recent troubleshooting information whilst **not** reproducing the bug: 

- [2017-10-26 10:45 about:support.json.txt](https://github.com/mozilla-services/screenshots/files/1417798/2017-10-26.10.45.about.support.json.txt)
- [2017-10-26 10:45 about:support.txt](https://github.com/mozilla-services/screenshots/files/1417799/2017-10-26.10.45.about.support.txt)


Thanks again!
