### ISSUE TITLE
Some users aren't appearing as logged-in on their own shots

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3129] opened 2017-07-14 15:18 UTC
We got a second abuse report for a user that just wanted to delete their own shot. Since the abuse button doesn't even show up when you are logged in, I suspect something is going wrong with their login state.

**Comment by wresuolc** [comment] 2017-07-20 17:52
@SoftVision-CosminMuntean have you ever seen this?  Any ideas on how to reproduce?

Restarting the browser with a shot page open maybe?

**Comment by SoftVision-CosminMuntean** [comment] 2017-08-03 13:28
I have investigated this, but I haven't managed to reproduce this behavior.

I saw a long time ago a similar behavior at Page Shot migration I think. I have also encountered this when I have opened a shot in a Container tab. 
I will keep an eye on this to see if I can find some STR.

**Comment by johngruen** [comment] 2017-08-17 18:47
Closing as dupe of #3322

**Closed by johngruen** 2017-08-17 18:47 UTC
