### ISSUE TITLE
Firefox Screenshots icon does not adjust color for themes

### ISSUE THREAD

**Issue by MikkCZ** [mozilla-services/screenshots#3078] opened 2017-07-03 10:44 UTC
Using the nightly, Firefox Screenshots toolbar icon does not adjust its color for compact dark theme and stays ugly gray, making it very hard to see. Also note, than the overflow menus are always light, so in the overflow menu the icon color should stay the same as for the default theme. Not sure, how this can be done in an add-on, but the Firefox built-in tools icons like Bookmark do it.

**Comment by johngruen** [comment] 2017-07-03 13:21
Yeah, this is a known issue. Looks like the patch that lets us fix this just landed: https://bugzilla.mozilla.org/show_bug.cgi?id=1329242

**Comment by wresuolc** [comment] 2017-07-03 15:45
Closing as a dupe of #2887

**Closed by wresuolc** 2017-07-03 15:45 UTC
