### ISSUE TITLE
Screenshots not working on http://www.udem.edu.mx/Esp/Noticias-Eventos/Pages/Eventos/2018/marzo/Hackatour-Monterrey-2018.aspx

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#4216] opened 2018-03-12 15:50 UTC
Originally filed as https://bugzilla.mozilla.org/show_bug.cgi?id=1444657:

> Navigate to: http://www.udem.edu.mx/Esp/Noticias-Eventos/Pages/Eventos/2018/marzo/Hackatour-Monterrey-2018.aspx
> 
> Try to take an screenshot.. nothing happen this happen with al the pages under http://www.udem.edu.mx

**Comment by ianb** [comment] 2018-03-12 15:51
I looked at this, and there's a CSS rule on the page of `body > iframe {display: none}`.

It's possible we could add `!important` to our display value on the iframe.

**Comment by chenba** [comment] 2018-03-22 22:33
This is a duplicate of #4148

**Closed by chenba** 2018-03-22 22:33 UTC
