### ISSUE TITLE
"Save" and "Download" buttons are misleading

### ISSUE THREAD

**Issue by saberworks** [mozilla-services/screenshots#3603] opened 2017-10-06 20:02 UTC
A button with the label "Save" should save the screenshot to my computer.  As it is, the "Save" button uploads my screenshot (along with extra data [see issue #3602]) to your servers.  A developer stated that the "cloud" icon was added to make the action of the button more clear.  In my opinion, the addition of a cloud icon to a button with label "Save" just makes it more confusing.  Does it save it to my computer or upload it somewhere?  Further, the screenshot isn't actually "saved forever" as it would be if it was saved on my local filesystem.  Rather, it's uploaded to your server and retained for a fixed period of time, after which it is deleted.  I think this should be renamed to "Share" or "Upload" or something.

A button with the label "Download" should save some remote file to my computer.  As it is, the current "Download" button takes an already-local bit of data and saves it locally.  This should be renamed to "Save."

**Comment by jxcl** [comment] 2017-10-06 21:30
I'd like to add on to what saberworks has said.

I, and many people like me, use Firefox primarily because it provides better protections against sending my private data to any third parties. Any buttons that send data to another server should be clearly marked as doing such; any other solution erodes the trust that so many people have placed in Firefox.

**Comment by FatOrangutan** [comment] 2017-10-08 02:31
I think the following is more intuitive:

Local save: floppy disk icon (maybe with an arrow pointing downward) with a tooltip that says "Save"
Cloud save: the current icon (cloud + upward arrow) with the button labelled as 'Upload.'

**Comment by raquo** [comment] 2017-11-23 01:41
This is a very bad violation of user trust. Today I've inadvertently uploaded extremely sensitive data to some random mozilla server exposed to the internet thanks to this bug. To make it worse, the server refused to delete the screenshot, repeatedly throwing some error in an alert().

A sufficient fix for the security implications of this bug would be to change one word: "Save" to "Upload".

@johngruen Judging by your metadata changes it seems like you've had an internal discussion about this and decided that this bug is not important... am I reading that right? If so, why? Are you not convinced that this is an important problem, or is there something else?

**Comment by raquo** [comment] 2017-11-23 01:59
The incorrect translation string is `saveScreenshotSelectedArea`. From a github search, it seems to only be used in that mislabeled upload button, [here](https://github.com/mozilla-services/screenshots/blob/ee62951e9d5ee516fc4661b056899070d90bbb25/addon/webextension/selector/ui.js#L423).

**Comment by chenba** [comment] 2017-11-27 14:43
@raquo If you remember or can still reproduce it, could you please give me info on the error you encountered when you tried to delete the shot?

**Comment by raquo** [comment] 2017-11-27 17:41
Actually I was able to reproduce it just now: The error simply says "Error deleting shot" in an alert(). In the console, the request to `/api/delete-shot` throws a 401 error with the content "Not logged in". I'm not sure what it wants me to be logged into, I don't use any Firefox services requiring a login.

[delete-shot request har extract.txt](https://github.com/mozilla-services/screenshots/files/1506912/delete-shot.har.extract.txt)

Fun fact: in today's example the website in question happened to be using [Sentry](https://sentry.io) error reporting, so the URL of the failed request was sent there. So not only was the screenshot not deleted, it was also shared.

**Comment by chenba** [comment] 2017-11-27 22:44
@raquo Thanks for the information.  By looking at the attached request info I think the issue with the delete is that no cookies were sent.  You can try disabling whatever is blocking the cookies from being sent.  (The relevant code is at https://github.com/mozilla-services/screenshots/blob/ee62951e9d5ee516fc4661b056899070d90bbb25/server/src/server.js#L204)

**Comment by raquo** [comment] 2017-11-28 00:26
@chenba That's the server code of `screenshots.firefox.com`, right? I have third party cookies disabled in Firefox settings. Whitelisting `https://screenshots.firefox.com` for cookies fixed that. At least I was able to delete my screenshots, thanks.

This whole thing really breaks my mental model of browser features being distinct from websites...

**Comment by julienw** [comment] 2017-11-29 13:11
Somebody just reported to me the same thing as @raquo. I myself have difficulties pressing the right button even after some months. This definitely needs to be clearer.

**Comment by flodolo** [comment] 2017-11-29 14:08
Passing by note: asking localizers to change existing translations to make it clearer is not the correct approach. It needs to be fixed upstream, e.g. "Upload to server" instead of "Save").

**Comment by clouserw** [comment] 2018-08-31 15:46
duplicate of #3503 

I'm going to close this as a duplicate of #3503 as both issues have evolved to be the same thing and that issue was filed first.

**Closed by clouserw** 2018-08-31 15:46 UTC
Labels: firefox, needs:priority

**Comment by julienw** [comment] 2018-08-31 18:32
As long as the issue is fixed, I'm fine :)
