### ISSUE TITLE
Variable response time for the primary screenshots UI to appear after clicking toolbar item.

### ISSUE THREAD

**Issue by ckarlof** [mozilla-services/screenshots#3867] opened 2017-11-30 22:13 UTC
On some pages it appears almost instantly and on others it seems to take 500-1000ms. For example, I see a significantly delay when trying to take a shot on https://github.com/mozilla-services/screenshots/issues.

**Comment by Softvision-CristinaBadescu** [comment] 2017-12-04 12:39
Thanks for reporting this. However, it seems to be a dupe of #3861.

**Comment by ckarlof** [comment] 2017-12-04 17:53
The issue I'm reporting is different to the one in #3861, but they might have the same cause. The delay I'm reporting is between "Click the "Take a Screenshot" button from "Page Actions" menu" and seeing the the overlay that offers the controls to save the page.

**Comment by chenba** [comment] 2017-12-04 19:57
@ckarlof do you have other pages where this is consistently happening?  The overlay appears almost instantly for me on https://github.com/mozilla-services/screenshots/issues

**Comment by 6a68** [comment] 2017-12-04 20:14
@chenba I've seen a noticeable delay on heavyweight pages, like imdb.com, cnn.com, theverge.com. 

That said, I'm not able to reproduce any lengthy delays with github URLs.

I think this is a legit perf bug; reopening.

**Comment by 6a68** [comment] 2017-12-04 20:15
Also, since we are now tracking the time from page action / context menu click to overlay being shown, we might be able to find some worst-case domains from GA

**Comment by ianb** [comment] 2017-12-04 20:33
GA won't have (shouldn't have) any information that would point to the source domain

I wonder if the `iframe.onload` handler might fire slowly or oddly given a queue of tasks on a page?

**Comment by wresuolc** [comment] 2017-12-05 17:01
@ckarlof what version of Firefox are you using?  Nightly had a bug where the page refreshed before displaying for a few days

**Comment by ckarlof** [comment] 2017-12-05 17:39
Interesting, I am using Nightly, and I can't easily reproduce anymore. Perhaps that was the issue.

**Comment by chenba** [comment] 2017-12-05 17:41
Marking this as a dup of #3692.  Closing.

**Closed by chenba** 2017-12-05 17:41 UTC
