### ISSUE TITLE
"Error: Data is not valid png/jpg image" error is displayed if the "Copy" button is used on selections > 600x600px

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3850] opened 2017-11-28 15:09 UTC
[Notes]:
- This issue is not reproducible for small selections (under 600x600 px).
- This issue is not reproducible on the provided [Nightly try build](https://treeherder.mozilla.org/#/jobs?repo=try&revision=5696688afd8f) with Screenshots 25.0.0. 

[Affected versions]:
- Nightly 59.0a1
- Screenshots 25.0.0 

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Steps to reproduce]:
1. Open latest Nightly (59.0a1) build and navigate to any website.
2. Perform a selection over 600x600 px on the page.
3. Click the "Copy" button and observe the behavior.

[Expected result]:
- The image is copied to the clipboard and a notification is displayed.

[Actual result]:
- A "Error: Data is not valid png/jpg image" system error notification is displayed.

[Notes]:
- Here is a screen shot with browser console errors:
![copy image](https://user-images.githubusercontent.com/19226534/33326811-a3f470e4-d45e-11e7-83ee-7f2d7dc15ed2.png)

- Here is a screen recording with the issue:
![copy](https://user-images.githubusercontent.com/19226534/33326876-d465efb4-d45e-11e7-9426-7e07145de897.gif)

**Comment by chenba** [comment] 2017-11-28 15:30
It's not the image dimensions but rather the amount of data.  A shot > 600 x 600px from https://news.ycombinator.com wouldn't cause this error since it's mostly text.

**Comment by chenba** [comment] 2017-11-28 15:38
It's also not consistent across OSes.  I was able to copy a full page of IMDB to the clipboard in Linux but not Windows.

**Comment by SoftVision-CosminMuntean** [comment] 2017-11-28 15:55
@chenba I was able to reproduce this issue on Arch Linux x64 and also on Ubuntu 14.04 x64.

**Comment by chenba** [comment] 2017-11-28 22:59
The limit is 500kB, which is when clipboard data moves from memory to temp files.  This bug was recently introduced into Firefox.  The last working version of Nightly is 2017-11-27-10-04-33; 2017-11-27-22-04-46 is the first build where this bug appeared.

(The reason it was working for me in Linux during original testing was that I had a slightly outdated version of Nightly.)

**Comment by ianb** [comment] 2017-11-28 23:04
We should create a bug in Bugzilla. I'm not seeing any bug with just copying a large image in a new Nightly, so I'm guessing this is specific to an extension? Ideally we could create an extension that demonstrates this. Maybe it's sufficient just to allocate a big buffer of nulls?

**Comment by 6a68** [comment] 2017-11-28 23:07
You can use mozregression to get to the exact patch that introduced the breakage.

**Comment by chenba** [comment] 2017-11-29 05:07
501kB of nulls wouldn't work because not only it's extension specific, but also specific to images.  There were some changes to imgTools, which necessitated this change: https://hg.mozilla.org/mozilla-central/diff/e60f002f07d0/toolkit/components/extensions/ext-clipboard.js.  That's the most relevant change I can find at least; I haven't found exactly where the bug is or how the 500kB limit comes into play.  The imgTools changes came from https://bugzilla.mozilla.org/show_bug.cgi?id=1420223.  

@6a68 Thanks.  I already got the regression range; I'll try to remember to use mozregession in the future.

**Comment by chenba** [comment] 2017-11-29 06:38
Ok, I suspect that the line `let str = String.fromCharCode.apply(String, new Uint8Array(imageData));` is the problem.  That `apply` call is hitting the argument length limit.

**Comment by chenba** [comment] 2017-11-29 15:32
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1421655.

**Comment by chenba** [comment] 2017-12-01 15:02
I can confirm this is fixed in the latest Nightly.

**Closed by chenba** 2017-12-01 15:02 UTC

**Comment by Softvision-CristinaBadescu** [comment] 2017-12-04 12:32
This issue is no longer reproducible using Firefox Screenshots 25.0.0, on latest Nightly build 59.0a1 (2017-12-03), on Windows 10 x64, Mac 10.12.6 and Ubuntu 14.04 x64.
