### ISSUE TITLE
Screenshots Setting Cookies for All Firefox Users Who Visit a Shot

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4819] opened 2018-08-27 19:17 UTC
Perhaps this is a vestige of PageShot not being a systems addon, but now that Screenshots is shipped with Firefox, and with the way auth works, cookies are set for all Firefox users who have ever visited a shot.  The cookies are unnecessary for people who are only looking at shots and never use the addon.

#### STR

1. Create a shot and copy the URL to the shot
1. Start an instance of Firefox with a fresh profile
1. Go to the URL copied in step 1
1. Open the dev tool and go to Storage -> Cookies

#### Expected

No user/auth related cookies (`user` and `user.sig`) set by the Screenshots site.

#### Actual

Cookies are set.

**Comment by punamdahiya** [comment] 2018-08-27 19:31
Screenshot of cookies seen
<img width="1247" alt="cookies" src="https://user-images.githubusercontent.com/597734/44681324-1b9a9f80-a9f5-11e8-8b12-436f807572d3.png">

**Comment by clouserw** [comment] 2018-08-29 15:36
_csrf is generated by middleware for all visitors.  The a/b test cookies are valid -- we might be testing non-authed users.  There is no ID cookie here.  I'll close this bug.

**Comment by chenba** [comment] 2018-08-29 20:43
I retested this because I want to know if I'm losing it.  Luckily maybe I'm not because I was able reproduce it.  Here's a shot of the cookies

![image](https://user-images.githubusercontent.com/198055/44814006-fb0f4880-aba0-11e8-92e3-fd849541b247.png)

@SoftVision-CosminMuntean Could you give it a try?

**Comment by SoftVision-CosminMuntean** [comment] 2018-08-30 13:05
I have also managed to reproduce this issue. I have reproduce this with Screenshots (34.0.0) dev version and also with Screenshots 33.0.0 production version on Windows 7 x64, Mac 10.13 and Arch Linux 4.12.
Here is a screenshot of the cookies:
![cookies](https://user-images.githubusercontent.com/19226534/44853257-21e78080-ac6e-11e8-9566-98639cbaef4f.png)


However, it seems that it is not reproducible if you create a shot with Firefox Screenshots (34.0.0) dev version and load the shot in another instance of Firefox where the Screenshots (32.1.0) production version it's installed (probably because are different servers).

Unfortunately, I haven't managed to test this local with FxA SIgnIn pull request since I get some errors after I run the "./bin/run-server" command.

**Comment by chenba** [comment] 2018-08-30 14:12
> probably because are different servers

Thanks, @SoftVision-CosminMuntean.  That is the reason.

**Comment by punamdahiya** [comment] 2018-08-30 19:38
Finally able to reproduce this issue on localhost by generating xpi using SCREENSHOTS_BACKEND=http://localhost:10080 make unsigned_bootstrap_xpi and installing add-on in nightly.

We are calling /set-login-cookie for all users irrespective of ownership after they are registered 
https://github.com/mozilla-services/screenshots/blob/master/addon/webextension/sitehelper.js#L60

Possible fix is to check for info.ownership before calling sendBackupCookieRequest(info.authHeaders). This fix needs to be in extension and will be rolled out with firefox release

**Comment by chenba** [comment] 2018-10-01 16:04
This only affects new profiles.  After this fix, you should not see the user and user.sig cookies until you uploaded a shot.

**Closed** 2018-10-03 17:39 UTC
Labels: firefox
