### ISSUE TITLE
[Annotations] Edit button does not have its badge when you first use Firefox Screenshots

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#4344] opened 2018-04-18 12:01 UTC
It seems that this is a Nightly regression. I have also logged this issue in Bugzilla: #[1454914](https://bugzilla.mozilla.org/show_bug.cgi?id=1454914).

[Affected versions]:
- Nightly 61.0a1, Build ID: 20180417225505

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the Firefox browser and navigate to any website.
2. Click the "Page actions" menu and select "Take a Screenshot" option.
3. Skip the onboarding tour.
4. Click the "Save visible" button and select the "Save" button.
5. Observe the "Edit" (Pencil) button.

[Expected result]:
- The button has a blue circle that has a star in it.

[Actual result]:
- The button has no badge.

[Regression]:
- It seems that this is a Nightly regression. Using mozregression tools I have found a regression window. Here are the results:
Last good revision: ae45e56c3c71ae23084e9ef549c3d58880add8a1
First bad revision: 87b552f9c09b68a255eeb84c5c554384b0c1231a
Pushlog: https://goo.gl/pYTBYX

From the pushlog it seems that bug [1452496](https://bugzilla.mozilla.org/show_bug.cgi?id=1452496) has caused this issue. 

[Notes]:
- This issue is also reproducible on an older Nightly 61.0a1 build ID 20180108220132 with latest Firefox Screenshots v32.0.0dev installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html) and on the latest Beta 60.0b13 with latest Firefox Screenshots v30.1.0.
- This issue is not reproducible on the latest Firefox Beta 60.0b12 with Firefox Screenshots 30.1.0.
- This issue is not reproducible on the latest Firefox Release 59.0.2 with Firefox Screenshots 25.0.0.
- Here is a screen recording with this issue:
![screenshots - edit button](https://user-images.githubusercontent.com/31244235/38930641-420a5676-4319-11e8-9766-e85a8db7d27d.gif)

**Comment by chenba** [comment] 2018-04-18 13:05
This is a duplicate of #4337.

**Comment by chenba** [comment] 2018-04-18 14:52
@Softvision-CristinaBadescu Thanks for finding that bug!

**Comment by chenba** [comment] 2018-04-20 23:17
Looks like it's how React 16 handles server side rendering.  (See https://github.com/facebook/react/issues/10591.)  We need to do a state change in `componentDidMount` to update the page on the client side.

**Closed** 2018-04-25 22:30 UTC

**Comment by Softvision-CristinaBadescu** [comment] 2018-04-26 11:58
Thanks for fixing this. This issue is no longer reproducible using the latest Firefox Screenshots v32.1.1dev, on latest Nightly build 61.0a1 (2018-04-25), on Windows 10 x64, Mac 10.13.4 Ubuntu 14.04 x64.
