### ISSUE TITLE
[Annotations] The image disappears in edit mode if you hover a color that is positioned under the image

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#4438] opened 2018-05-11 15:08 UTC
[Affected versions]:
- Nightly 62.0a1
- Screenshots 32.1.0dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- The "extensions.install.requireBuiltInCerts" is set to "false".
- Have the Screenshots 32.1.0dev version installed from [here](https://screenshots.stage.mozaws.net/homepage/install-test-local.html), on a new clean profile.
- Have a saved shot link.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to the saved shot link.
2. Click the "Edit this image" button.
3. Resize the browser so the image is positioned under any of the colors row.
4. Hover one color from the row and observe the behavior.

[Expected result]:
- The color gets focused.

[Actual result]:
- The image disappears.

[Notes]:
- The image reappears if you hover other colors from a different row or if you click the "Color Picker" button.
- Here is a screen recording with the issue:
![ss - image](https://user-images.githubusercontent.com/31244235/39931521-5086dd20-5546-11e8-9a2e-5d7bd5e0bfd0.gif)

**Comment by chenba** [comment] 2018-05-11 15:40
I cannot reproduce this on Windows or Linux.

**Comment by SoftVision-CosminMuntean** [comment] 2018-05-11 16:05
The issue is reproducible only if the image is positioned under the color row. If the image is not positioned under the color row you can vertically resize the browser from the button part of it in order to change  the image position.
See this screen recording: 
![image](https://user-images.githubusercontent.com/19226534/39934335-24b3a6bc-554e-11e8-80d6-562f07d487fe.gif)

**Comment by SoftVision-CosminMuntean** [comment] 2018-05-14 09:15
@chenba it seems that this is a Nightly regression (started with the builds from 10th May). On which version of Firefox did you test the issue?

However, since is a Nightly regression I have logged the issue in Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1461281

**Comment by chenba** [comment] 2018-05-14 13:56
The versions I used were newer than May 10th.  I just tried it with the latest Nightly on Windows and still cannot reproduce it.

**Comment by SoftVision-CosminMuntean** [comment] 2018-05-17 09:30
The issue is no longer reproducible on latest Nightly (62.0a1) build using the latest Screenshots dev version. Tested on Windows 7 x64, Windows 10 x64 and Mac 10.13.

Probably the issue was fixed by #4389.

**Closed by SoftVision-CosminMuntean** 2018-05-17 09:30 UTC
Labels: [QA]:Normal issue
