### ISSUE TITLE
If you dismiss the Screenshots overlay after finishing the Onboarding tour, Screenshots does not work in the current tab

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2636] opened 2017-04-11 13:07 UTC
[Notes]:
- Screenshots works on the other tabs or on new opened tabs.

[Affected versions]:
- Firefox 54.0a2 (Build ID:20170407004017)
- Screenshots 6.0.2123

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Firefox Screenshots (6.0.2123) custom build is installed on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to any website.
2. Click the Firefox Screenshots button from browser toolbar. 
3. Follow the Onbording tour and dismiss the selection.
4. Click the Screenshots button from the browser toolbar.
5. Observe the browser behavior.

[Expected result]:
- The Screenshots overlay covers the page.

[Actual result]:
- A "Whoa! Firefox Screenshots went haywire" error is displayed.

[Additional Notes]:
- This issue is reproducible on dev and stage server.
- I haven't managed to reproduce the issue with the Firefox Screenshots custom build created yesterday (2017-04-10).
- Here is a screenshots with browser console errors after clicking the Screenshots button:
![onbording second click on screenshots](https://cloud.githubusercontent.com/assets/19226534/24910473/962bd3d8-1ed0-11e7-8203-fb9c1f585238.png)
- Here is a screen recording with the issue:
![second click after onboarding fff](https://cloud.githubusercontent.com/assets/19226534/24910502/aacd942a-1ed0-11e7-8764-04b3638245f6.gif)

**Comment by ianb** [comment] 2017-04-12 18:53
I can't reproduce this, I'm pretty sure it's another regression that was fixed by #2634

**Closed by ianb** 2017-04-12 18:53 UTC
Labels: beta blocker

**Comment by SoftVision-EmilPasca** [comment] 2017-04-13 13:54
This issue is no longer reproducible on the latest Firefox Screenshots (v. 6.2.1984), dev and stage custom builds.
