### ISSUE TITLE
 Screenshots is disabled when "Never remember history" is enabled

### ISSUE THREAD

**Issue by FahimaZulfath** [mozilla-services/screenshots#3196] opened 2017-07-23 05:53 UTC
User Agent: Mozilla/5.0 (Windows NT 6.2; rv:55.0) Gecko/20100101 Firefox/55.0
Build ID: 20170720101431
Step to Reproduce
1) Open Firefox Developer Edition with a clean profile.
2) Navigate to about:config page.
3) Click on "I accept the risk".
4) Search for "extensions.screenshots.system-disabled" pref and set it to false.
Actual Result: Screenshot fails to work. Showing popup as " Screenshots is disabled in private browsing mode". 
Expected Result: Screenshot must work in normal browsing.

![bug](https://user-images.githubusercontent.com/22166013/28497001-0a3eb60a-6f99-11e7-919d-8e248ca2acee.jpg)

**Comment by SoftVision-CosminMuntean** [comment] 2017-07-24 08:27
@FahimaZulfath Thanks for reporting this!
Is there a chance that you have set the "Never remember history" option from "about:preferences#privacy" page?

**Comment by FahimaZulfath** [comment] 2017-07-24 18:02
No I didn't checked "never remember history" from about:preferences.

**Comment by SoftVision-CosminMuntean** [comment] 2017-07-25 12:42
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0
Firefox 55.0b11, Build ID: 20170720101431

@FahimaZulfath I can't reproduce this on a new clean profile. Do you have any configuration related to history or cookies? Or you can reproduce it without any changes on a new clean profile?

**Comment by johngruen** [comment] 2017-08-17 18:36
I'm gonna snoop on this

**Comment by johngruen** [comment] 2017-10-23 18:44
Closing this as a dupe

**Closed by johngruen** 2017-10-23 18:44 UTC
Labels: Firefox, needs:product, P3
