### ISSUE TITLE
No favicon for wnba.com site

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/screenshots#1936] opened 2016-11-08 23:10 UTC
https://pageshot.net/__version__ (3c8e0e5):

```json
{
  "source": "https://github.com/mozilla-services/pageshot/",
  "description": "Page Shot application server",
  "version": "November 08, 2016 17:16:00 UTC",
  "commit": "3c8e0e5",
  "contentOrigin": "pageshot-usercontent.net",
  "commitLog": "https://github.com/mozilla-services/pageshot/commits/3c8e0e5",
  "unincludedCommits": "https://github.com/mozilla-services/pageshot/compare/3c8e0e5...master"
}
```

---

![my_shots](https://cloud.githubusercontent.com/assets/557895/20121192/f5d570da-a5c4-11e6-8855-246d0d57689d.png)

Looks like we're trying to load favicon from https://pageshot-usercontent.net/proxy?url=http%3A%2F%2Fak-static.cms.nba.com%2Fwp-content%2Fthemes%2Fwnba-parent%2Fimg%2Ffavicon.ico&sig=2DtIECbmgncg9CScokyqb9R69ew

That looks right to me. And this is the URL I see when I go trolling through view-source on wnba.com:
https://ak-static.cms.nba.com/wp-content/themes/wnba-parent/img/favicon.ico, which gives me this 16x16px hot mess: ![](https://ak-static.cms.nba.com/wp-content/themes/wnba-parent/img/favicon.ico)

Just seems odd that this isn't displaying in my "My Shots" page, and I'm guessing not something so bizarrely wnba.com specific but probably tips at a slightly larger issue.

**Comment by pdehaan** [comment] 2016-11-08 23:16
Also just saw from my glorious screenshot that i.imgur.com doesn't display a favicon.
My imgur.com link is https://pageshot.net/5CTo5Zdpptijg7YU/i.imgur.com (or http://i.imgur.com/6rlglQr.jpg).
I assume that would have tried loading http://i.imgur.com/favicon.ico.

Here's a DOM snapshot of that PageShot tile, which doesn't seem to have a `<div class="favicon">...</div>`:

![my_shots](https://cloud.githubusercontent.com/assets/557895/20121435/46dd8570-a5c6-11e6-9644-4d73df4eb9b5.png)

```html
<a href="https://pageshot.net/5CTo5Zdpptijg7YU/i.imgur.com" class="shot" data-reactid="52">
  <div class="shot-image-container" style="background-image:url(https://pageshot.net/images/4bc777e7-eeb2-405d-a933-fc2e7a1a0099);" data-reactid="53"></div>
  <div class="title-container" data-reactid="54">
    <h4 data-reactid="55">6rlglQr.jpg (JPEG Image, 700&nbsp;×&nbsp;1000 pixels)</h4>
  </div>
  <div class="link-container" data-reactid="56">
    <div class="shot-url" data-reactid="57">i.imgur.com</div>
  </div>
  <div class="inner-border" data-reactid="58"></div>
</a>
```

**Comment by pdehaan** [comment] 2016-11-08 23:17
But worth noting that those look like two similar but unrelated issues.

- wnba.com seems to have a favicon DOM element that isn't loading.
- i.imgur.com doesnt seem to have a favicon DOM element.

**Comment by ianb** [comment] 2016-11-14 23:19
To reproduce:

```sh
curl 'http://localhost:10081/proxy?url=http%3A%2F%2Fak-static.cms.nba.com%2Fwp-content%2Fthemes%2Fwnba-parent%2Fimg%2Ffavicon.ico&sig=3kiP8pII9a1x6PdDl0NhhSua2EM'
```

The problem is that this gives a redirect (to https in this case), and the proxier doesn't handle redirects.  We can't echo the redirect, we have to generate another proxy URL and send that.

The intermittents on imgur might be because of some http and some https links and the same redirects?

**Comment by johngruen** [comment] 2017-06-28 17:27
closing in favor of the general bug: #2648

**Closed by johngruen** 2017-06-28 17:27 UTC
