### ISSUE TITLE
Clicking the "Terms" and "Privacy Notice" links from Onboarding tour, open a new blank tab 

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2699] opened 2017-04-18 12:29 UTC
[Affected versions]:
- Nightly 55.0a1 (Build ID:20170418030220)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Nightly build with Screenshots installed and a clean profile.
- The "extensions.screenshots.system-disabled" pref is set to false.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click the Firefox Screenshots button from browser toolbar. 
3. Click the "Terms"/"Privacy Notice" link from Onboarding tour.
4. Observe the browser behavior.

[Expected result]:
- A new tab is opened and you are redirected to the terms/privacy page.

[Actual result]:
- A new blank tab is opened.

[Notes]:
- The issue is also reproducible on stage server.
- Here is a screen recording with the issue:
![onboarding tour](https://cloud.githubusercontent.com/assets/19226534/25130550/3b4061fc-244b-11e7-9dee-1b817d74663f.gif)

**Comment by 6a68** [comment] 2017-04-18 18:29
Debugging this requires using regular devtools, because the onboarding slides load inside an iframe in the content page.

Looking at the link in the devtools inspector, it looks like the localized strings are getting inserted *next to* an empty link:

<img width="633" alt="screen shot 2017-04-18 at 11 27 40 am" src="https://cloud.githubusercontent.com/assets/96396/25146854/4fc85cc2-242a-11e7-9bda-b8a29210935d.png">

**Comment by 6a68** [comment] 2017-04-18 18:47
@pdehaan pointed out that the weirdness in the inspector might be a devtools nightly bug, since the text is clickable, has the correct link style, and hovering the link text shows the correct URL.

**Comment by 6a68** [comment] 2017-04-18 18:59
Testing the latest addon against Dev Edition, the links work fine. I think this might be a browser bug.

**Comment by 6a68** [comment] 2017-04-18 19:31
I'm not sure where to take this from here. @Standard8, any thoughts on whether this might be a browser bug (and if so, how to find that bug)?

**Comment by Standard8** [comment] 2017-04-18 19:44
@6a68 If it works in dev edition, I'd suggest using [mozregression](http://mozilla.github.io/mozregression/) to hunt down the regression causing patch.

**Comment by 6a68** [comment] 2017-04-18 21:12
sweet! mozregression is new to me, thanks for that :+1:

**Comment by 6a68** [comment] 2017-04-18 21:57
OK! Turns out this bug was introduced when we switched the iframe to a moz-extension URL in commit da197660.

**Comment by ianb** [comment] 2017-04-18 21:59
Maybe the most reliable fix for this would just be to use `callBackground` and have the background page open the link.  At least we know that would work.

**Comment by 6a68** [comment] 2017-04-18 22:43
Kris noticed that this bug only occurs if e10s is enabled. Filed [bugzilla bug 1357589](https://bugzil.la/1357589) at Kris's request.

I'll go ahead and implement the callBackground workaround, for now.

**Closed** 2017-04-19 16:52 UTC
Labels: gamma blocker
