### ISSUE TITLE
Saved shot link is not copied to clipboard [hard to reproduce]

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla-services/screenshots#3130] opened 2017-07-14 15:50 UTC
[Affected versions]:
- Firefox 55.0b8

[Affected Platforms]:
- All Windows
- All Linux

[Prerequisites]:
- Have a Firefox profile with the Screenshots add-on provided in the email (10.4.4171) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to a website (eg. www.wikipedia.org)
2. Select one word from the website's content and press Ctrl+C.
3. Click the Screenshots button from the toolbar.
4. Perform a selection and save it. 
5. Open a new tab and press Ctrl+P on the URL bar.
6. Observe the pasted string.

[Expected result]:
- The link to the saved shot is pasted in the URL bar. 

[Actual result]:
- The text previously copied from the website is pasted in the URL bar.

[Additional Notes]:
- Attached a screen recording of the issue:

![pasted issue](https://user-images.githubusercontent.com/26000308/28219564-2ea60c1c-68c5-11e7-899c-d997f20c7616.gif)

**Comment by 6a68** [comment] 2017-07-14 19:07
Hmm.

On Windows, if I set the debugger [inside the link copying code](), I see:
- doc.execCommand('copy') returns `true`
- `el` exists and is in the DOM
- `el.value` exists and is the URL
- `doc.defaultView.getSelection().toString()` (i.e. `window.getSelection`) is an empty string

Looks like the copy command thinks it's succeeding, but isn't.

However, if I go to the shot page, open the share card, and click 'Copy', the URL is copied successfully.

Seems weird that this would break in this specific version of screenshots.

**Comment by ianb** [comment] 2017-07-14 19:08
I just tested on Windows, with the patched XPI, and it worked for me.  I was using Nightly 2017-07-03 (but it looks like I should try with Beta)

**Comment by 6a68** [comment] 2017-07-14 19:15
I just retried in beta and nightly, and couldn't repro the bug on either. Maybe it only affects a fresh profile? (How could that be?)

**Comment by ianb** [comment] 2017-07-14 19:20
I just tried on latest Nightly and Beta (Windows) and it also worked.  That said, some but not all SoftVision testers have reliably reproduced this.

**Comment by SoftVision-CosminMuntean** [comment] 2017-07-18 14:10
It seems that this issue is only reproducible on Beta 55 using a new clean profile. Reproducible on Windows and also on Mac OS with or without the provided Screenshots xpi.

[Steps to reproduce]:
1. Start Beta 55 with a new clean profile and navigate to "about:config" page.
2. Set the "extensions.screenshots.system-disabled" pref to false.
3. Navigate to any website and copy any word from the page.
4. Click the Screenshots button from the toolbar and dismiss the Screenshots tour.
5. Perform a selection and save it.
6. Open a new tab, focus the URL bar and press "Ctrl+V".
7. Observe the pasted string.

[Expected result]:
- The link to the saved shot is pasted in the URL bar.

[Actual result]:
- The text previously copied from the website is pasted in the URL bar.

[Notes]:
- The issue is no longer reproducible if the browser is restarted.
- Here is a screen recording with the issue: https://goo.gl/a9kvry
- I have managed to reproduce the issue on Beta 55 using a new custom Screenshots dev build created from GitHub repository. But, on Nightly is not reproducible.

**Comment by wresuolc** [comment] 2017-07-20 17:50
@SoftVision-CosminMuntean is this still reproducible?  If so, can you give more steps? thanks

**Comment by SoftVision-CosminMuntean** [comment] 2017-07-21 14:28
@wresuolc  I can still reproduce this issue, but only on Beta 55 with a new clean profile. The issue is reproducible following the steps provided in the above comment. I have also provided a screen recording.

I have also tried with Nightly but I haven't managed to reproduce it.
Please let me know if you need more information.

**Comment by johngruen** [comment] 2017-08-17 18:46
@SoftVision-CosminMuntean would you mind giving this a look?

**Comment by SoftVision-CosminMuntean** [comment] 2017-08-18 15:16
I can still reproduce this issue on latest Beta (56.0b3) build using a new clean profile. Is weird because is not reproducible on latest Nightly builds. 
Also, using mozregression tool I have tried to find if this issue is a Firefox one and if it was fixed on Nightly, but I haven't managed to find a bad build of Nightly to go further.

**Comment by SoftVision-CosminMuntean** [comment] 2017-08-24 13:57
Now that Screenshots (10.12.0) is enabled by default in Beta (56.0b4), I have retested this issue and it seems that is no longer reproducible.  But the issue is reproducible on Firefox (55.0.2) with Screenshots 10.12.0.

Probably this issue is only reproducible when Screenshots is disabled by default and you manually enable it from "about:config" page.

**Comment by johngruen** [comment] 2017-08-24 21:23
I am now seeing this on MacOS in Nightly 57 with 10.12.0

**Comment by 6a68** [comment] 2017-08-24 21:53
> I am now seeing this on MacOS in Nightly 57 with 10.12.0

I'm unable to reproduce :-(

**Comment by ianb** [comment] 2017-08-24 21:54
This seems to be related to the profile.

Looking through the code, there's not a lot of code paths that would make this happen: specifically, showing a popup saying the URL was copied, and opening a new tab to the right page, and then ultimately not copy the URL.

Experimenting shows that `doc.execCommand("copy")` will return true but not copy anything if there is no text selected. The relevant code in clipboard.js:

```js
          let el = doc.createElement("textarea");
          doc.body.appendChild(el);
          el.value = text;
          el.select();
          const copied = doc.execCommand("copy");
```

So I see two possibilities: `text` is empty, or `el.select()` fails.

If text is empty, that value is the result of calling `callBackground("takeShot",...)`, which doesn't have many conditionals, and ends with `return shot.viewUrl;` – which is used right before to open the tab, which we know works. There is a possibility this still isn't returned properly due to some communication error, though corruption of the message seems unlikely.

We could/should at least put in a check for `text` being empty in clipboard.js, send a Sentry message, and return false for copied.  Maybe we could use `doc.activeElement` to also confirm that the selection worked (and again send a Sentry message)

**Comment by 6a68** [comment] 2017-08-24 21:58
Seems impossible/silly, but I wonder if the issue is that we need to shove a setTimeout in there somewhere. Maybe check that the element actually is in the DOM before trying to execCommand on it? Maybe wait a beat between select() and copy()?

**Comment by 6a68** [comment] 2017-08-24 21:58
It's great to know it can be reproduced on Mac, that rules out platform-specific issues

**Comment by 6a68** [comment] 2017-09-21 17:51
@SoftVision-CosminMuntean Can you still reproduce this issue? We added some error logging in #3406, but those errors aren't showing up in Sentry at all, and the other clipboard-related error shows up very, very rarely.

**Comment by SoftVision-CosminMuntean** [comment] 2017-09-22 12:12
I have retested this issue on latest Firefox (55.0.3) release with Beta 56.0 and also on latest Nightly (58.0a1) build, but I have reproduced the issue only one time when I have updated Beta 56.0b12 to Beta 56.0 using a new clean profile. 

I have tried the same scenario multiple times, but I haven't managed to reproduce the issue again. I think we can close this issue and if I will find another scenario to reproduce this, I will reopen it.

**Comment by 6a68** [comment] 2017-10-31 16:30
Reopening: seems like this issue still occurs (#3571)

**Comment by 6a68** [comment] 2017-10-31 16:31
@SoftVision-CosminMuntean Could you try to repro this again?

**Comment by dall2812** [comment] 2017-11-01 08:49
Still happening in 56.0.2, 64 bit, Windows 10, using the old profile as always. Can I do something to help you debug it?

**Comment by johngruen** [comment] 2017-11-01 15:43
@dall2812 could you go to about:support and let me know what version of screenshots it says you have

**Comment by dall2812** [comment] 2017-11-02 08:18
@johngruen 
> could you go to about:support and let me know what version of screenshots it says you have

It's 10.12.0.

**Comment by SoftVision-CosminMuntean** [comment] 2017-11-03 09:05
I did more investigations on this issue, but I have managed to reproduce this issue only with Beta 55.0b8 on a clean profile with Screenshots (10.3.0). The issue is not reproducible after the browser is restarted.

[Steps to reproduce]:
1. Download Beta 55.0b8 from here: [Windows](https://archive.mozilla.org/pub/firefox/releases/55.0b8/win64/en-US/), [Mac OS](https://archive.mozilla.org/pub/firefox/releases/55.0b8/mac/en-US/)
2. Open the browser using a new clean profile.
3. Go to "about:config" and set the "extensions.screenshots.system-disabled" pref to false.
4. In a new tab navigate to any website and copy any word from the page.
5. Click the Screenshots button from the toolbar and dismiss the Screenshots tour.
6. Perform a selection and save it.
7. Open a new tab, focus the URL bar and press "Windows: Ctrl+V"  "Mac OS: Cmd+V".
8. Observe the pasted string.

[Expected result]:
- The link to the saved shot is pasted in the URL bar.

[Actual result]:
- The text previously copied from the website is pasted in the URL bar.

[Notes]:
- Probably there are more versions of Firefox where the issue is reproducible. 
- The issue is no longer reproducible after the browser is restarted.
- Here is a screen recording with the issue: https://goo.gl/fYb7dh

**Comment by ianb** [comment] 2019-02-07 21:35
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).

**Closed by ianb** 2019-02-07 21:35 UTC
Labels: P2, defect, firefox, server wontfix
