### ISSUE TITLE
Empty and unusable icon where Screenshots is supposed to be in Fx55 RC1

### ISSUE THREAD

**Issue by rvandermeulen** [mozilla-services/screenshots#3257] opened 2017-08-01 18:02 UTC
From IRC discussion in #fx-team, I'm still seeing bug 1381963 with Fx55 RC1 currently on the Beta channel. I've confirmed that version 10.9.0 of the Screenshots addon is installed.

Screenshot:
![screenshots](https://user-images.githubusercontent.com/3661247/28839557-08a5c79a-76c2-11e7-8b76-050ffb62d228.png)

Browser console logs:
DataError: Data provided to an operation does not meet requirements. (unknown)
	wrapMethods/cls.prototype[method] resource://gre/modules/IndexedDB.jsm:103:47
	get resource://gre/modules/ExtensionParent.jsm:1319:22
	next self-hosted:1179:9
CustomizableUI:unable to normalize widget  CustomizableUI.jsm:2179
aId is undefined  CustomizableUI.jsm:1267
	isSpecialWidget resource:///modules/CustomizableUI.jsm:1267:5
	getWidgetProvider resource:///modules/CustomizableUI.jsm:888:9
	wrapWidget resource:///modules/CustomizableUI.jsm:500:20
	createWidget resource:///modules/CustomizableUI.jsm:3308:12
	build chrome://browser/content/ext-browserAction.js:118:18
	onManifestEntry chrome://browser/content/ext-browserAction.js:104:5
	asyncEmitManifestEntry resource://gre/modules/ExtensionCommon.jsm:920:14
	next self-hosted:1179:9
[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIWebNavigation.loadURIWithOptions]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: chrome://global/content/bindings/browser.xml :: loadURIWithFlags/< :: line 150"  data: no]  (unknown)
	loadURIWithFlags/< chrome://global/content/bindings/browser.xml:150:15
	_wrapURIChangeCall chrome://global/content/bindings/browser.xml:43:17
	loadURIWithFlags chrome://global/content/bindings/browser.xml:149:13
	loadURI/< chrome://global/content/bindings/browser.xml:114:15
	_wrapURIChangeCall chrome://global/content/bindings/browser.xml:43:17
	loadURI chrome://global/content/bindings/browser.xml:113:13
	build chrome://extensions/content/ext-backgroundPage.js:42:5
	next self-hosted:1179:9

**Comment by wresuolc** [comment] 2017-08-01 18:04
This was on win10

**Comment by 6a68** [comment] 2017-08-01 18:24
OK, I can confirm the IndexedDB error appears on Win 10 Beta, in cases where Screenshots works, so we can ignore this bit:

>  DataError: Data provided to an operation does not meet requirements. (unknown)
wrapMethods/cls.prototype[method] resource://gre/modules/IndexedDB.jsm:103:47
get resource://gre/modules/ExtensionParent.jsm:1319:22
next self-hosted:1179:9

My steps to generate this error: start Beta on Win 10 in a fresh profile with Screenshots preffed off. Manually flip the `system-disabled` pref to `false`. The IndexedDB error appears and the Screenshots button appears.

**Comment by 6a68** [comment] 2017-08-01 18:38
I think what the other errors mean is that the widget ID isn't getting passed from the browserAction code to the CustomizableUI code.

I wonder if the browserAction code expects our addon's ID to be in the manifest? Not sure why this would start breaking *now*.

browserAction passes `this.id` to CUI [here](https://dxr.mozilla.org/mozilla-beta/source/browser/components/extensions/ext-browserAction.js#119)
and creates `this.id` from the `id` in the extension (does that mean, from the manifest?) plus a string [here](https://dxr.mozilla.org/mozilla-beta/source/browser/components/extensions/ext-browserAction.js#74)
Note that our webextension's manifest does _not_ have an id: [manifest on dxr](https://dxr.mozilla.org/mozilla-beta/source/browser/extensions/screenshots/webextension/manifest.json)


Seems like the id should just be "-browser-action" if there's no ID, though.

**Comment by gijsk** [comment] 2017-08-01 18:48
FWIW, I think the errors may not be super helpful here. See also the stack and discussion in https://bugzilla.mozilla.org/show_bug.cgi?id=1378081 , which I wontfixed because my impression was the issue there was caused by the add-on SDK and/or the add-on in question. If WebExtensions are hitting the same thing maybe there's an underlying issue that we don't yet understand - but it comes back to, as the initial comment notes, the `gPalette.has()` check returning true here: https://dxr.mozilla.org/mozilla-central/rev/36f95aeb4c77f7cf3b3366583008cd6e4b6b1dba/browser/components/customizableui/CustomizableUI.jsm#2448 which would mean that there is already a browser action widget created (and not destroyed) for the webextension in question. This would mean `normalizeWidget` returns null, and wrapWidget gets called with `null`, which would result in the stack you're seeing.

**Comment by gijsk** [comment] 2017-08-01 18:50
There are other reasons as to why the normalizeWidget code would return null, but those seem less likely causes here. Of course, a debugger on this code would help. You could also try enabling logging of CUI internals by flipping the `browser.uiCustomization.debug` pref to true.

**Comment by 6a68** [comment] 2017-08-01 19:03
This is pretty weird! I'm running a copy of @rvandermeulen's busted profile on a Win 10 machine, and the broken button is visible, while `extensions.screenshots.system-disabled` is set to true.

Toggling system-disabled doesn't affect the toolbar at all; the half-broken button sits there regardless.

**Comment by johngruen** [comment] 2017-08-01 19:08
@6a68 i am able to reproduce that on RC1. On Beta 13 I see the button but it does not toggle over to the onboarding button even on a clean profile

**Comment by johngruen** [comment] 2017-08-01 19:28
Errr, update on previous. Creating new profiles on windows is wonky.

**Comment by 6a68** [comment] 2017-08-01 19:51
OK, here's what I'm seeing on windows 10, using beta builds from the ftp site, https://ftp.mozilla.org/pub/firefox/releases:

- beta 9: button works fine
- beta 10, 11, 12: button is broken, toggling `system-disabled` pref does nothing
- beta 13: button works fine

My steps here:
- download the installer
- install firefox
- at the last step of the installer, leave the box checked to start firefox
- create a fresh profile in the profile picker
- toggle the `system-disabled` pref in about:config, see what happens

When the button fully appears (with an icon), it always seems to be fully functional.

Could someone else confirm this?

**Comment by 6a68** [comment] 2017-08-01 20:03
If I create a profile in beta 11 (busted), then upgrade to beta 13, the button is fixed.

In this case, system-disabled was set to true before and after the restart, meaning Screenshots was preffed off by the SHIELD study.

**Comment by johngruen** [comment] 2017-08-01 20:04
6a68 what version of the add-on is in beta 11..? that's know to be busted, correct?

**Comment by 6a68** [comment] 2017-08-01 20:29
@johngruen OK, this is all a little bit confusing, so I made a table

| works? | Firefox version | Screenshots version | date |
| -----| ------| ------ | ------ |
| ✅ | beta 9 | July 14 | 10.3.0 |
| ❌ | beta 10 | July 17 | 10.5.0 | 
| ❌| beta 11 | July 20 | 10.5.0 |
| ✅ | beta 12 | July 24 | 10.8.0 |
| ✅ | beta 13 | July 28 | 10.9.0 |

Beta 10-11 / Screenshots 10.5.0 is broken differently than in this report: the icon path isn't correct, but you can see the empty button getting inserted and removed when the `extensions.screenshots.system-disabled` pref is flipped.

I'm not able to repro this error where there's empty button space, but nothing happens when the `system-disabled` pref is toggled.

Trying now in RC1

**Comment by johngruen** [comment] 2017-08-01 20:31
@6a68 beta 10 and 11 were known to be broken...part of why we bumped to 10.8. One of the issues causing the dot bump was that i hadn't passed a newly named version of the starred icon into the add-on start up code.

**Comment by 6a68** [comment] 2017-08-01 20:33
> @6a68 beta 10 and 11 were known to be broken...part of why we bumped to 10.8. One of the issues causing the dot bump was that i hadn't passed a newly named version of the starred icon into the add-on start up code.

Right, that's the bug I'm seeing there. But again, in that case, the empty button is clearly being added and removed from the toolbar.

This bug is something different, and I'm not able to repro in a clean profile.

**Comment by 6a68** [comment] 2017-08-01 20:34
I can't repro this in RC1 on Win 10 in a fresh profile.

**Comment by 6a68** [comment] 2017-08-01 21:07
I can't repro this bug when upgrading from beta 13 to RC 1, though that seems to be good STR for @rvandermeulen

**Comment by rvandermeulen** [comment] 2017-08-01 21:12
There was some question as to whether Portable Firefox was playing a role here (since that's where I first encountered the bug). Unfortunately, I was just able to independently reproduce the problem again on another computer running regular Firefox Beta.

I started with Fx55b13 and screenshots enabled. Manually did an update check and updated to RC1. On restart, I get the empty button reported here. When I restarted Firefox again, I went through a progression of no button at all (or corresponding gap) to empty button, to screenshots icon (but not actually functional - clicking on it does nothing).

**Comment by rvandermeulen** [comment] 2017-08-01 21:15
I also verified that in this broken state, I was seeing the same browser console warnings as before. Also, both the system and system-disabled prefs were showing as false.

However, after restarting Firefox for a third time, it's now completely disabled and the system-disabled pref is set to true. Don't know if it's been talking to SHIELD in the mean time or something.

**Comment by 6a68** [comment] 2017-08-01 22:00
OK, my current best guess as to a possible bug:

1. the screenshots pref observer starts at startup time, but not the webextension
2. suppose the pref is initially disabled, then shield flips the pref to enabled, before the webextension starts
3. the 'sessionstore-session-restored' event fires, and the [`appStartupPromise`](https://github.com/mozilla-services/screenshots/blob/master/addon/bootstrap.js#L59) resolves
4. multiple `appStartupPromise.then(handleStartup)` calls were queued up (say, [here](https://github.com/mozilla-services/screenshots/blob/master/addon/bootstrap.js#L129) and also [here](https://github.com/mozilla-services/screenshots/blob/master/addon/bootstrap.js#L44)), and so `handleStartup` is called twice in short succession 
5. [ ... chaos intensifies ... ]
6. broken button in your toolbar

I'm going to try adding some pref flips inside bootstrap.js to simulate this edge case, and see what breaks.

**Comment by 6a68** [comment] 2017-08-01 23:51
Fixed by #3260.

**Closed by 6a68** 2017-08-01 23:51 UTC
