### ISSUE TITLE
Background image not captured

### ISSUE THREAD

**Issue by THPallab** [mozilla-services/screenshots#1859] opened 2016-10-28 05:57 UTC
If we want to take a snap shot of a blogspot & similar sights with a large margin, the background shows some error. Sometimes the full background is gone & sometimes just a portion of it comes. It must be fixed to become more user friendly.

**STR:**
1. First open your firefox browser.
2. Go to blogspot.com. (https://tanvir4pallab.blogspot.com/)
3. Try to take a long snap shot with backgrounds.

Actual Result:  You can see your snap shot without the page background.
Expected Result: We expect our snap shot with all the contents as well as the backgrounds.

I have reproduced with Firefox 51.0a2 on Windows 7, 32 Bits
Build ID    20161027004020
User Agent  Mozilla/5.0 (Windows NT 6.1; rv:51.0) Gecko/20100101 Firefox/51.0 

This is the screen shot with the bug.

![page-shot-2016-10-28 t h p s blog](https://cloud.githubusercontent.com/assets/23113744/19796333/606609fa-9d05-11e6-91cf-380aef01884c.png)

**Comment by ianb** [comment] 2016-11-14 23:02
This works for me; example of a full page capture, e.g., [in this shot](https://pageshot.net/M5qrvK3quMQVuxn3/tanvir4pallab.blogspot.com)

**Comment by SoftVision-CosminMuntean** [comment] 2016-11-15 14:11
I can still reproduce this issue on Windows 7, Windows 10 and Ubuntu 16.04 with the latest Firefox (49.0.2) and latest Nightly (53.0a1) build. I have tested this using the latest Page Shot v.2.6.201611151209 installed from stage server.

However, the issue is not reproducible on Mac OS 10.11.

**Comment by wresuolc** [comment] 2017-06-28 17:56
This looks fixed now:  https://screenshots.firefox.com/qZ66k9WklEW0YeJr/tanvir4pallab.blogspot.com

**Closed by wresuolc** 2017-06-28 17:56 UTC
