### ISSUE TITLE
The metrics page is way too long

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#4449] opened 2018-05-14 22:35 UTC
The metrics page has way too much data, with user histograms going back to 2016. The page is 300k pixels long, triggers the "a web page is slowing down your browser" warning while loading, and takes 23 seconds to load for me.

We should limit the data to a reasonably short, recent period of time...or just get rid of it

**Comment by wresuolc** [comment] 2018-05-16 15:56
duplicate of #4278

**Closed by wresuolc** 2018-05-16 15:56 UTC
