### ISSUE TITLE
PageShot overlay is wrongly activated when its toolbar button is clicked more than once

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla-services/screenshots#2244] opened 2017-03-01 16:34 UTC
[Notes]:
- When pressing the "Esc" key only the top PageShot overlay instance is dismissed.
- Every time the user is activating PageShot he is allowed to make a new selection.

[Affected versions]:
- Firefox 51 and up
- Mozilla Page Shot 5.2.3505

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest version of the Page Shot(dev-5.2.3505) add-on was previously installed on a clean profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to any page.
2. Click twice or more times on the the PageShot button from the browser toolbar.
3. Observe the browser behavior.

[Expected result]:
- A single semi-transparent grey overlay is displayed over the page content no matter how many times the button is clicked.

[Actual result]:
- A new semi-transparent grey overlay is displayed on top of the other for each click.

[Additional Notes]:
- Here is a screen recording with the issue:
![pageshot_activating_toolbar](https://cloud.githubusercontent.com/assets/20083658/23469857/87fa24ec-fead-11e6-9102-cfed92897052.gif)

**Comment by SoftVision-EmilPasca** [comment] 2017-03-09 08:36
I have retested this issue using the latest Page Shot (v. 5.2.14901) custom build and is no longer reproducible.

**Comment by SoftVision-EmilPasca** [comment] 2017-03-10 16:28
The issue is still reproducible when retesting this with the latest Page Shot (v. 5.2.1906) custom build.

**Comment by ianb** [comment] 2017-03-10 19:30
The current behavior should be that when you click the button a second time, the interface is turned off very briefly then turned back on.  Is this what you are seeing, or are you still seeing overlapping interfaces?  I'm not seeing a problem with the latest build.

**Comment by SoftVision-EmilPasca** [comment] 2017-03-13 12:22
I have retested this issue using the latest Page Shot (v. 5.2.4829) custom build and is no longer reproducible.

**Comment by SoftVision-CosminMuntean** [comment] 2017-04-11 12:05
It seems that this issue is reproducible on the latest Firefox Screenshots custom build, created from GitHub repository.  
I can't reproduce the issue on the  Screenshots custom build created yesterday.

**Comment by ianb** [comment] 2017-04-11 17:29
I think this was introduced yesterday (after I closed this ticket) by #2591 and fixed by #2634

**Closed by ianb** 2017-04-11 17:29 UTC
Labels: beta blocker, Bug

**Comment by SoftVision-EmilPasca** [comment] 2017-04-13 13:55
This issue is no longer reproducible on the latest Firefox Screenshots (v. 6.2.1984), dev and stage custom builds.
