### ISSUE TITLE
Windows 8.1 64bit FF56.0.1 save to disk fails 

### ISSUE THREAD

**Issue by JNicoll** [mozilla-services/screenshots#3659] opened 2017-10-19 19:37 UTC
I tried to screenshot a paused TV programme on the BBC  iPlayer website.  App appeared to work but nothing was saved.   A yellow dot was displayed next to the main downloads icon.    Opening the downloads pane I saw error "Failed" and if you mouse over that you see "Failed - blob resource".

But uploading the image to the cloud worked.   Saving other screenshots from different TV programmes on the same website also worked.

I wonder if the problem is that the filename to which the screenshot is saved includes the tV programme's name, and that's not been sanitised properly.  In this case the programme name ended in "?", which is an invalid character in a Windows filename.

Test it by going here: https://www.bbc.co.uk/iplayer/episode/b09b6y8s/eat-well-for-less-series-4-episode-5

(though I suppose in a few days' time that episode might be unavailable).  Don't click any of the buttons on the page, just try to save a screenshot.   The TV programme's name is "Eat Well for Less?".

**Comment by SoftVision-CosminMuntean** [comment] 2017-10-20 11:07
@JNicoll thanks for reporting this!

This is a known issue and was already fixed in #3084. However, the issue is no longer reproducible on latest Beta 57.0b9 and latest Nightly (58.0a1) build, so the issue will be fixed in the next Firefox release.

**Closed by SoftVision-CosminMuntean** 2017-10-20 11:07 UTC

**Comment by JNicoll** [comment] 2017-10-20 12:33
Not according to
https://github.com/mozilla-services/screenshots/pull/3084/commits/960986420f1bebec3b640479b172f5193c5eea1c

where there's no code to get rid of a question mark.

**Comment by SoftVision-CosminMuntean** [comment] 2017-10-20 13:47
Sorry, I added the wrong fix. Here is the Bugzilla bug that fixed this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1403665

**Comment by JNicoll** [comment] 2017-10-20 13:56
AH, thank-you.
