### ISSUE TITLE
Screenshot Button is not visible 

### ISSUE THREAD

**Issue by mMARUF** [mozilla-services/screenshots#3177] opened 2017-07-21 11:38 UTC
Build ID       :      20170720101431
User Agent :       Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0

Steps to reproduce : 
1. Enable Firefox Screenshots from about:config from ( 
   extensions.screenshots.system-disabled )

Actual Result:    You will see that the color screenshot button is not perfectly 
                  visible. The button color matches with the theme color.
                  And if you change the the theme from the option of devtools, then 
                  also it is not perfectly visible. I think the button is broken.

Expected Result : The screenshot button color should be different so that it is visible.

![capture](https://user-images.githubusercontent.com/10638506/28462052-529824cc-6e3b-11e7-9a8f-8345398fc1a2.png)

**Comment by SoftVision-CosminMuntean** [comment] 2017-07-24 13:32
@mMARUF thanks for reporting this. Unfortunately this issue is a dupe of #3125.  Also, the issue is already fixed on the latest version of Screenshots.

**Closed by SoftVision-CosminMuntean** 2017-07-24 13:32 UTC
