### ISSUE TITLE
Let me hide or edit the URL domain

### ISSUE THREAD

**Issue by gerdneuman** [mozilla-services/screenshots#4230] opened 2018-03-15 09:38 UTC
Usually I use screenshot to post bugs or problem to software support forums when I have a particular problem with a certain software or plugin. What stops me for using Firefox Screenshots for this is that I do not want to share the website name (Domain) when sharing the screenshot:

![image](https://user-images.githubusercontent.com/12525563/37455078-8a0c0d0e-283c-11e8-81cb-70c1e879dfbc.png)

I can edit the shot title but cannot edit the shot's shown Domain which is shown in the description but also in the shots URL.

Could there be an option to hide or edit this Domain / URL information.

I know I can just download / copy a shot without uploading it, but many forums do not support embedding images directly but only allow links.

**Comment by wresuolc** [comment] 2018-03-15 15:49
Duplicate of #3460

**Closed by wresuolc** 2018-03-15 15:49 UTC
