### ISSUE TITLE
[Enhancement] Please add option to include URL

### ISSUE THREAD

**Issue by dserodio** [mozilla-services/screenshots#3928] opened 2017-12-28 16:52 UTC
When reporting bugs in web apps, it's often useful to show the URL alongside the screenshot. Please add an option to include URL bar, or some other way of including the URL in the screenshot.

**Comment by johngruen** [comment] 2018-01-03 16:55
@dserodio we actually had this but backed it out for security reasons. I have a bug filed, so i am closing this as a dupe of #3251

**Closed by johngruen** 2018-01-03 16:55 UTC
