### ISSUE TITLE
Firefox Screenshots icon is not visible after first enabling Screenshots 10.5.0

### ISSUE THREAD

**Issue by IuliaCristescu4** [mozilla-services/screenshots#3145] opened 2017-07-18 09:21 UTC
[Affected versions]:
- Firefox 55.0b10 build1 (20170717063821)

[Affected platforms]:
- Windows 10 x64
- Mac OS X 10.11.6 
- Ubuntu 16.04 x64

[Steps to reproduce]:
1. Launch Firefox with a clean profile.
2. Enable Firefox Screenshots.
 - inspect the Screenshots icon from the toolbar
3. Disable Firefox Screenshots.
4. Repeat step 2. 
5. Access the Firefox Screenshots button.
6. Close the onboarding tour tab. 
7. Repeat steps 3, 4 and 5. 
 -  inspect the Screenshots icon from the toolbar.
8. Skip the onboarding tour in order to open Firefox Screenshots. 
9. Repeat steps 3 and 4. 

[Expected result]:
Firefox Screenshots icon is available on the toolbar and there are no visibility or accessibility problems.

[Actual result]:
- Firefox Screenshots icon is not visible on the toolbar after the enabling - a blank space (with hover effect) is generated instead of the corresponding button
- It stays invisible until it is accessed 
- Until the overlay is opened, disabling and enabling back Firefox Screenshots does not fix the problem

The issue is not reproducible on older versions of Firefox Beta or Firefox Screenshots.
For more details, access the following video: https://goo.gl/cMiQYw

**Comment by SoftVision-PaulOiegas** [comment] 2017-07-18 09:30
Hi @IuliaCristescu4 and thanks for reporting this. Unfortunately the issue is a dupe of #3125. 
Also, it was already fixed on dev version and will probably land on next Beta build, so I'm gonna close this one.

**Closed by SoftVision-PaulOiegas** 2017-07-18 09:30 UTC
