### ISSUE TITLE
metricsgraphics labels are not correctly captured

### ISSUE THREAD

**Issue by trink** [mozilla-services/screenshots#5131] opened 2018-11-02 20:12 UTC
https://screenshots.firefox.com/9EIeF1qbNXNLZayH/hsadmin.trink.com
https://hsadmin.trink.com/dashboard_output/send.html

**Comment by johngruen** [comment] 2018-11-06 17:54
What OS are you using?

**Comment by johngruen** [comment] 2018-11-06 17:55
https://screenshots.firefox.com/K1liHaAQ1SqEXPnW/hsadmin.trink.com

**Comment by SoftVision-CosminMuntean** [comment] 2018-11-08 09:08
I have managed to reproduce this issue on Windows 10 x64, Windows 7 x64. However, I haven't managed to reproduce it on Mac OS 10.13 and Linux (Debian 9).
The issue is reproducible on latest Firefox 63.0.1 release and on latest Nightly (65.0a1) build with Screenshots production version and also with the latest Screenshots (34.0.0) dev version.

It seems that the issue is reproducible on Full Pages, Visible Pages and automatically selections. But it most of the cases the shot is correctly saved when a manual selection is saved.

**Comment by johngruen** [comment] 2018-11-12 17:09
@trink are there transparency layers in your site? We had a bug in Side View that might be related: https://github.com/mozilla/side-view/issues/396

Suggests this might be a platform issue or something? @6a68 will poke FF people to see if there's a known issue here.

**Comment by trink** [comment] 2018-11-12 18:10
Yeah in the default metricsgraphics styling
```.mg-x-axis text, .mg-y-axis text, .mg-histogram .axis text {

    fill: black;
    font-size: 0.9rem;
    opacity: 0.6;
}
```

**Comment by 6a68** [comment] 2018-11-13 23:12
@trink Could you try enabling webrender and see if that fixes the issue?

**Comment by 6a68** [comment] 2018-11-13 23:19
Possibly related, courtesy of @kbrosnan: https://bugzilla.mozilla.org/show_bug.cgi?id=1360592

**Comment by 6a68** [comment] 2018-11-20 18:52
Closing as an upstream bug. @trink, feel free to reopen if needed

**Closed by 6a68** 2018-11-20 18:52 UTC
