### ISSUE TITLE
Screenshot from a long web page

### ISSUE THREAD

**Issue by michs** [mozilla-services/screenshots#3837] opened 2017-11-26 14:48 UTC
**Steps to reproduce:**

Save a webpage with a long article as screenshot, choose option "whole page". (Used Firefox on Mac OS Yosemite)

**Actual results:**

The screenshot is saved, but the lower part of the pages is clipped. The maximal screenshot length seems to be limited to 10 000 pixels. The screenshot can be saved completely when the zoom of the page is changed in that way that the page needs less than 10 000 pixels length to be displayed.

**Expected results:**

Screenshots should not be limited in length in order to allow screenshots with a page zoom "100%" for longer texts too.

**Comment by wresuolc** [comment] 2017-11-27 16:41
The 10k pixel limit is by design so we can limit the size of the files.  As our product matures we hope to change that limit, but for now it's in place.  I'm going to close this as there are a few other bugs asking for the same thing.

**Closed by wresuolc** 2017-11-27 16:41 UTC
