### ISSUE TITLE
Shot Selection Starts on Vertical Scrollbar Click

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4406] opened 2018-05-09 14:12 UTC
#### STR:

1. Go to a page with a vertical scrollbar (e.g. https://github.com)
1. Start Screenshots
1. Click on the vertical scrollbar
1. Move mouse cursor back into the page

#### Expected:

Page scrolled.

#### Actual:

Page scrolled, and drag selection started.

#### Note
The fix is mentioned in Jared's comment: https://github.com/mozilla-services/screenshots/pull/4401#issuecomment-387524590

**Comment by SoftVision-CosminMuntean** [comment] 2018-05-09 14:32
I think that this issue is a dupe of #2698.
The issue is reproducible on Windows and Linux, but not on Mac OS. @chenba on which OS can you reproduce the issue?

**Closed** 2018-05-09 14:43 UTC
Labels: firefox
